// Code generated by ent, DO NOT EDIT.

package poolcapacityalertevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldID, id))
}

// StateID applies equality check predicate on the "state_id" field. It's identical to StateIDEQ.
func StateID(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldStateID, v))
}

// Episode applies equality check predicate on the "episode" field. It's identical to EpisodeEQ.
func Episode(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldEpisode, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldGroupID, v))
}

// GroupGeneration applies equality check predicate on the "group_generation" field. It's identical to GroupGenerationEQ.
func GroupGeneration(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldGroupGeneration, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAccountID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAPIKeyID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldUserID, v))
}

// BillingType applies equality check predicate on the "billing_type" field. It's identical to BillingTypeEQ.
func BillingType(v int8) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldBillingType, v))
}

// GroupName applies equality check predicate on the "group_name" field. It's identical to GroupNameEQ.
func GroupName(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldGroupName, v))
}

// AccountName applies equality check predicate on the "account_name" field. It's identical to AccountNameEQ.
func AccountName(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAccountName, v))
}

// APIKeyName applies equality check predicate on the "api_key_name" field. It's identical to APIKeyNameEQ.
func APIKeyName(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAPIKeyName, v))
}

// UserEmail applies equality check predicate on the "user_email" field. It's identical to UserEmailEQ.
func UserEmail(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldUserEmail, v))
}

// PredictedRequests applies equality check predicate on the "predicted_requests" field. It's identical to PredictedRequestsEQ.
func PredictedRequests(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldPredictedRequests, v))
}

// ThresholdRequests applies equality check predicate on the "threshold_requests" field. It's identical to ThresholdRequestsEQ.
func ThresholdRequests(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldThresholdRequests, v))
}

// AccountRequests applies equality check predicate on the "account_requests" field. It's identical to AccountRequestsEQ.
func AccountRequests(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAccountRequests, v))
}

// APIKeyRequests applies equality check predicate on the "api_key_requests" field. It's identical to APIKeyRequestsEQ.
func APIKeyRequests(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAPIKeyRequests, v))
}

// WalletRequests applies equality check predicate on the "wallet_requests" field. It's identical to WalletRequestsEQ.
func WalletRequests(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldWalletRequests, v))
}

// AvgAccountCost applies equality check predicate on the "avg_account_cost" field. It's identical to AvgAccountCostEQ.
func AvgAccountCost(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAvgAccountCost, v))
}

// AvgActualCost applies equality check predicate on the "avg_actual_cost" field. It's identical to AvgActualCostEQ.
func AvgActualCost(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAvgActualCost, v))
}

// AccountRemaining applies equality check predicate on the "account_remaining" field. It's identical to AccountRemainingEQ.
func AccountRemaining(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAccountRemaining, v))
}

// APIKeyRemaining applies equality check predicate on the "api_key_remaining" field. It's identical to APIKeyRemainingEQ.
func APIKeyRemaining(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAPIKeyRemaining, v))
}

// WalletRemaining applies equality check predicate on the "wallet_remaining" field. It's identical to WalletRemainingEQ.
func WalletRemaining(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldWalletRemaining, v))
}

// SampleCount applies equality check predicate on the "sample_count" field. It's identical to SampleCountEQ.
func SampleCount(v int) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldSampleCount, v))
}

// Bottleneck applies equality check predicate on the "bottleneck" field. It's identical to BottleneckEQ.
func Bottleneck(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldBottleneck, v))
}

// QqbotAppID applies equality check predicate on the "qqbot_app_id" field. It's identical to QqbotAppIDEQ.
func QqbotAppID(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldQqbotAppID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// StateIDEQ applies the EQ predicate on the "state_id" field.
func StateIDEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldStateID, v))
}

// StateIDNEQ applies the NEQ predicate on the "state_id" field.
func StateIDNEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldStateID, v))
}

// StateIDIn applies the In predicate on the "state_id" field.
func StateIDIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldStateID, vs...))
}

// StateIDNotIn applies the NotIn predicate on the "state_id" field.
func StateIDNotIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldStateID, vs...))
}

// StateIDGT applies the GT predicate on the "state_id" field.
func StateIDGT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldStateID, v))
}

// StateIDGTE applies the GTE predicate on the "state_id" field.
func StateIDGTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldStateID, v))
}

// StateIDLT applies the LT predicate on the "state_id" field.
func StateIDLT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldStateID, v))
}

// StateIDLTE applies the LTE predicate on the "state_id" field.
func StateIDLTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldStateID, v))
}

// EpisodeEQ applies the EQ predicate on the "episode" field.
func EpisodeEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldEpisode, v))
}

// EpisodeNEQ applies the NEQ predicate on the "episode" field.
func EpisodeNEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldEpisode, v))
}

// EpisodeIn applies the In predicate on the "episode" field.
func EpisodeIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldEpisode, vs...))
}

// EpisodeNotIn applies the NotIn predicate on the "episode" field.
func EpisodeNotIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldEpisode, vs...))
}

// EpisodeGT applies the GT predicate on the "episode" field.
func EpisodeGT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldEpisode, v))
}

// EpisodeGTE applies the GTE predicate on the "episode" field.
func EpisodeGTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldEpisode, v))
}

// EpisodeLT applies the LT predicate on the "episode" field.
func EpisodeLT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldEpisode, v))
}

// EpisodeLTE applies the LTE predicate on the "episode" field.
func EpisodeLTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldEpisode, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldGroupID, v))
}

// GroupGenerationEQ applies the EQ predicate on the "group_generation" field.
func GroupGenerationEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldGroupGeneration, v))
}

// GroupGenerationNEQ applies the NEQ predicate on the "group_generation" field.
func GroupGenerationNEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldGroupGeneration, v))
}

// GroupGenerationIn applies the In predicate on the "group_generation" field.
func GroupGenerationIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldGroupGeneration, vs...))
}

// GroupGenerationNotIn applies the NotIn predicate on the "group_generation" field.
func GroupGenerationNotIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldGroupGeneration, vs...))
}

// GroupGenerationGT applies the GT predicate on the "group_generation" field.
func GroupGenerationGT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldGroupGeneration, v))
}

// GroupGenerationGTE applies the GTE predicate on the "group_generation" field.
func GroupGenerationGTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldGroupGeneration, v))
}

// GroupGenerationLT applies the LT predicate on the "group_generation" field.
func GroupGenerationLT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldGroupGeneration, v))
}

// GroupGenerationLTE applies the LTE predicate on the "group_generation" field.
func GroupGenerationLTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldGroupGeneration, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldAccountID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldAPIKeyID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldUserID, v))
}

// BillingTypeEQ applies the EQ predicate on the "billing_type" field.
func BillingTypeEQ(v int8) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldBillingType, v))
}

// BillingTypeNEQ applies the NEQ predicate on the "billing_type" field.
func BillingTypeNEQ(v int8) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldBillingType, v))
}

// BillingTypeIn applies the In predicate on the "billing_type" field.
func BillingTypeIn(vs ...int8) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldBillingType, vs...))
}

// BillingTypeNotIn applies the NotIn predicate on the "billing_type" field.
func BillingTypeNotIn(vs ...int8) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldBillingType, vs...))
}

// BillingTypeGT applies the GT predicate on the "billing_type" field.
func BillingTypeGT(v int8) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldBillingType, v))
}

// BillingTypeGTE applies the GTE predicate on the "billing_type" field.
func BillingTypeGTE(v int8) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldBillingType, v))
}

// BillingTypeLT applies the LT predicate on the "billing_type" field.
func BillingTypeLT(v int8) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldBillingType, v))
}

// BillingTypeLTE applies the LTE predicate on the "billing_type" field.
func BillingTypeLTE(v int8) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldBillingType, v))
}

// GroupNameEQ applies the EQ predicate on the "group_name" field.
func GroupNameEQ(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldGroupName, v))
}

// GroupNameNEQ applies the NEQ predicate on the "group_name" field.
func GroupNameNEQ(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldGroupName, v))
}

// GroupNameIn applies the In predicate on the "group_name" field.
func GroupNameIn(vs ...string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldGroupName, vs...))
}

// GroupNameNotIn applies the NotIn predicate on the "group_name" field.
func GroupNameNotIn(vs ...string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldGroupName, vs...))
}

// GroupNameGT applies the GT predicate on the "group_name" field.
func GroupNameGT(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldGroupName, v))
}

// GroupNameGTE applies the GTE predicate on the "group_name" field.
func GroupNameGTE(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldGroupName, v))
}

// GroupNameLT applies the LT predicate on the "group_name" field.
func GroupNameLT(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldGroupName, v))
}

// GroupNameLTE applies the LTE predicate on the "group_name" field.
func GroupNameLTE(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldGroupName, v))
}

// GroupNameContains applies the Contains predicate on the "group_name" field.
func GroupNameContains(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldContains(FieldGroupName, v))
}

// GroupNameHasPrefix applies the HasPrefix predicate on the "group_name" field.
func GroupNameHasPrefix(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldHasPrefix(FieldGroupName, v))
}

// GroupNameHasSuffix applies the HasSuffix predicate on the "group_name" field.
func GroupNameHasSuffix(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldHasSuffix(FieldGroupName, v))
}

// GroupNameEqualFold applies the EqualFold predicate on the "group_name" field.
func GroupNameEqualFold(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEqualFold(FieldGroupName, v))
}

// GroupNameContainsFold applies the ContainsFold predicate on the "group_name" field.
func GroupNameContainsFold(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldContainsFold(FieldGroupName, v))
}

// AccountNameEQ applies the EQ predicate on the "account_name" field.
func AccountNameEQ(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAccountName, v))
}

// AccountNameNEQ applies the NEQ predicate on the "account_name" field.
func AccountNameNEQ(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldAccountName, v))
}

// AccountNameIn applies the In predicate on the "account_name" field.
func AccountNameIn(vs ...string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldAccountName, vs...))
}

// AccountNameNotIn applies the NotIn predicate on the "account_name" field.
func AccountNameNotIn(vs ...string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldAccountName, vs...))
}

// AccountNameGT applies the GT predicate on the "account_name" field.
func AccountNameGT(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldAccountName, v))
}

// AccountNameGTE applies the GTE predicate on the "account_name" field.
func AccountNameGTE(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldAccountName, v))
}

// AccountNameLT applies the LT predicate on the "account_name" field.
func AccountNameLT(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldAccountName, v))
}

// AccountNameLTE applies the LTE predicate on the "account_name" field.
func AccountNameLTE(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldAccountName, v))
}

// AccountNameContains applies the Contains predicate on the "account_name" field.
func AccountNameContains(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldContains(FieldAccountName, v))
}

// AccountNameHasPrefix applies the HasPrefix predicate on the "account_name" field.
func AccountNameHasPrefix(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldHasPrefix(FieldAccountName, v))
}

// AccountNameHasSuffix applies the HasSuffix predicate on the "account_name" field.
func AccountNameHasSuffix(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldHasSuffix(FieldAccountName, v))
}

// AccountNameEqualFold applies the EqualFold predicate on the "account_name" field.
func AccountNameEqualFold(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEqualFold(FieldAccountName, v))
}

// AccountNameContainsFold applies the ContainsFold predicate on the "account_name" field.
func AccountNameContainsFold(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldContainsFold(FieldAccountName, v))
}

// APIKeyNameEQ applies the EQ predicate on the "api_key_name" field.
func APIKeyNameEQ(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAPIKeyName, v))
}

// APIKeyNameNEQ applies the NEQ predicate on the "api_key_name" field.
func APIKeyNameNEQ(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldAPIKeyName, v))
}

// APIKeyNameIn applies the In predicate on the "api_key_name" field.
func APIKeyNameIn(vs ...string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldAPIKeyName, vs...))
}

// APIKeyNameNotIn applies the NotIn predicate on the "api_key_name" field.
func APIKeyNameNotIn(vs ...string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldAPIKeyName, vs...))
}

// APIKeyNameGT applies the GT predicate on the "api_key_name" field.
func APIKeyNameGT(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldAPIKeyName, v))
}

// APIKeyNameGTE applies the GTE predicate on the "api_key_name" field.
func APIKeyNameGTE(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldAPIKeyName, v))
}

// APIKeyNameLT applies the LT predicate on the "api_key_name" field.
func APIKeyNameLT(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldAPIKeyName, v))
}

// APIKeyNameLTE applies the LTE predicate on the "api_key_name" field.
func APIKeyNameLTE(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldAPIKeyName, v))
}

// APIKeyNameContains applies the Contains predicate on the "api_key_name" field.
func APIKeyNameContains(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldContains(FieldAPIKeyName, v))
}

// APIKeyNameHasPrefix applies the HasPrefix predicate on the "api_key_name" field.
func APIKeyNameHasPrefix(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldHasPrefix(FieldAPIKeyName, v))
}

// APIKeyNameHasSuffix applies the HasSuffix predicate on the "api_key_name" field.
func APIKeyNameHasSuffix(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldHasSuffix(FieldAPIKeyName, v))
}

// APIKeyNameEqualFold applies the EqualFold predicate on the "api_key_name" field.
func APIKeyNameEqualFold(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEqualFold(FieldAPIKeyName, v))
}

// APIKeyNameContainsFold applies the ContainsFold predicate on the "api_key_name" field.
func APIKeyNameContainsFold(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldContainsFold(FieldAPIKeyName, v))
}

// UserEmailEQ applies the EQ predicate on the "user_email" field.
func UserEmailEQ(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldUserEmail, v))
}

// UserEmailNEQ applies the NEQ predicate on the "user_email" field.
func UserEmailNEQ(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldUserEmail, v))
}

// UserEmailIn applies the In predicate on the "user_email" field.
func UserEmailIn(vs ...string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldUserEmail, vs...))
}

// UserEmailNotIn applies the NotIn predicate on the "user_email" field.
func UserEmailNotIn(vs ...string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldUserEmail, vs...))
}

// UserEmailGT applies the GT predicate on the "user_email" field.
func UserEmailGT(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldUserEmail, v))
}

// UserEmailGTE applies the GTE predicate on the "user_email" field.
func UserEmailGTE(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldUserEmail, v))
}

// UserEmailLT applies the LT predicate on the "user_email" field.
func UserEmailLT(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldUserEmail, v))
}

// UserEmailLTE applies the LTE predicate on the "user_email" field.
func UserEmailLTE(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldUserEmail, v))
}

// UserEmailContains applies the Contains predicate on the "user_email" field.
func UserEmailContains(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldContains(FieldUserEmail, v))
}

// UserEmailHasPrefix applies the HasPrefix predicate on the "user_email" field.
func UserEmailHasPrefix(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldHasPrefix(FieldUserEmail, v))
}

// UserEmailHasSuffix applies the HasSuffix predicate on the "user_email" field.
func UserEmailHasSuffix(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldHasSuffix(FieldUserEmail, v))
}

// UserEmailEqualFold applies the EqualFold predicate on the "user_email" field.
func UserEmailEqualFold(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEqualFold(FieldUserEmail, v))
}

// UserEmailContainsFold applies the ContainsFold predicate on the "user_email" field.
func UserEmailContainsFold(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldContainsFold(FieldUserEmail, v))
}

// PredictedRequestsEQ applies the EQ predicate on the "predicted_requests" field.
func PredictedRequestsEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldPredictedRequests, v))
}

// PredictedRequestsNEQ applies the NEQ predicate on the "predicted_requests" field.
func PredictedRequestsNEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldPredictedRequests, v))
}

// PredictedRequestsIn applies the In predicate on the "predicted_requests" field.
func PredictedRequestsIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldPredictedRequests, vs...))
}

// PredictedRequestsNotIn applies the NotIn predicate on the "predicted_requests" field.
func PredictedRequestsNotIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldPredictedRequests, vs...))
}

// PredictedRequestsGT applies the GT predicate on the "predicted_requests" field.
func PredictedRequestsGT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldPredictedRequests, v))
}

// PredictedRequestsGTE applies the GTE predicate on the "predicted_requests" field.
func PredictedRequestsGTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldPredictedRequests, v))
}

// PredictedRequestsLT applies the LT predicate on the "predicted_requests" field.
func PredictedRequestsLT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldPredictedRequests, v))
}

// PredictedRequestsLTE applies the LTE predicate on the "predicted_requests" field.
func PredictedRequestsLTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldPredictedRequests, v))
}

// ThresholdRequestsEQ applies the EQ predicate on the "threshold_requests" field.
func ThresholdRequestsEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldThresholdRequests, v))
}

// ThresholdRequestsNEQ applies the NEQ predicate on the "threshold_requests" field.
func ThresholdRequestsNEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldThresholdRequests, v))
}

// ThresholdRequestsIn applies the In predicate on the "threshold_requests" field.
func ThresholdRequestsIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldThresholdRequests, vs...))
}

// ThresholdRequestsNotIn applies the NotIn predicate on the "threshold_requests" field.
func ThresholdRequestsNotIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldThresholdRequests, vs...))
}

// ThresholdRequestsGT applies the GT predicate on the "threshold_requests" field.
func ThresholdRequestsGT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldThresholdRequests, v))
}

// ThresholdRequestsGTE applies the GTE predicate on the "threshold_requests" field.
func ThresholdRequestsGTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldThresholdRequests, v))
}

// ThresholdRequestsLT applies the LT predicate on the "threshold_requests" field.
func ThresholdRequestsLT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldThresholdRequests, v))
}

// ThresholdRequestsLTE applies the LTE predicate on the "threshold_requests" field.
func ThresholdRequestsLTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldThresholdRequests, v))
}

// AccountRequestsEQ applies the EQ predicate on the "account_requests" field.
func AccountRequestsEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAccountRequests, v))
}

// AccountRequestsNEQ applies the NEQ predicate on the "account_requests" field.
func AccountRequestsNEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldAccountRequests, v))
}

// AccountRequestsIn applies the In predicate on the "account_requests" field.
func AccountRequestsIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldAccountRequests, vs...))
}

// AccountRequestsNotIn applies the NotIn predicate on the "account_requests" field.
func AccountRequestsNotIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldAccountRequests, vs...))
}

// AccountRequestsGT applies the GT predicate on the "account_requests" field.
func AccountRequestsGT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldAccountRequests, v))
}

// AccountRequestsGTE applies the GTE predicate on the "account_requests" field.
func AccountRequestsGTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldAccountRequests, v))
}

// AccountRequestsLT applies the LT predicate on the "account_requests" field.
func AccountRequestsLT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldAccountRequests, v))
}

// AccountRequestsLTE applies the LTE predicate on the "account_requests" field.
func AccountRequestsLTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldAccountRequests, v))
}

// AccountRequestsIsNil applies the IsNil predicate on the "account_requests" field.
func AccountRequestsIsNil() predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIsNull(FieldAccountRequests))
}

// AccountRequestsNotNil applies the NotNil predicate on the "account_requests" field.
func AccountRequestsNotNil() predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotNull(FieldAccountRequests))
}

// APIKeyRequestsEQ applies the EQ predicate on the "api_key_requests" field.
func APIKeyRequestsEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAPIKeyRequests, v))
}

// APIKeyRequestsNEQ applies the NEQ predicate on the "api_key_requests" field.
func APIKeyRequestsNEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldAPIKeyRequests, v))
}

// APIKeyRequestsIn applies the In predicate on the "api_key_requests" field.
func APIKeyRequestsIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldAPIKeyRequests, vs...))
}

// APIKeyRequestsNotIn applies the NotIn predicate on the "api_key_requests" field.
func APIKeyRequestsNotIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldAPIKeyRequests, vs...))
}

// APIKeyRequestsGT applies the GT predicate on the "api_key_requests" field.
func APIKeyRequestsGT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldAPIKeyRequests, v))
}

// APIKeyRequestsGTE applies the GTE predicate on the "api_key_requests" field.
func APIKeyRequestsGTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldAPIKeyRequests, v))
}

// APIKeyRequestsLT applies the LT predicate on the "api_key_requests" field.
func APIKeyRequestsLT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldAPIKeyRequests, v))
}

// APIKeyRequestsLTE applies the LTE predicate on the "api_key_requests" field.
func APIKeyRequestsLTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldAPIKeyRequests, v))
}

// APIKeyRequestsIsNil applies the IsNil predicate on the "api_key_requests" field.
func APIKeyRequestsIsNil() predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIsNull(FieldAPIKeyRequests))
}

// APIKeyRequestsNotNil applies the NotNil predicate on the "api_key_requests" field.
func APIKeyRequestsNotNil() predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotNull(FieldAPIKeyRequests))
}

// WalletRequestsEQ applies the EQ predicate on the "wallet_requests" field.
func WalletRequestsEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldWalletRequests, v))
}

// WalletRequestsNEQ applies the NEQ predicate on the "wallet_requests" field.
func WalletRequestsNEQ(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldWalletRequests, v))
}

// WalletRequestsIn applies the In predicate on the "wallet_requests" field.
func WalletRequestsIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldWalletRequests, vs...))
}

// WalletRequestsNotIn applies the NotIn predicate on the "wallet_requests" field.
func WalletRequestsNotIn(vs ...int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldWalletRequests, vs...))
}

// WalletRequestsGT applies the GT predicate on the "wallet_requests" field.
func WalletRequestsGT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldWalletRequests, v))
}

// WalletRequestsGTE applies the GTE predicate on the "wallet_requests" field.
func WalletRequestsGTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldWalletRequests, v))
}

// WalletRequestsLT applies the LT predicate on the "wallet_requests" field.
func WalletRequestsLT(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldWalletRequests, v))
}

// WalletRequestsLTE applies the LTE predicate on the "wallet_requests" field.
func WalletRequestsLTE(v int64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldWalletRequests, v))
}

// WalletRequestsIsNil applies the IsNil predicate on the "wallet_requests" field.
func WalletRequestsIsNil() predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIsNull(FieldWalletRequests))
}

// WalletRequestsNotNil applies the NotNil predicate on the "wallet_requests" field.
func WalletRequestsNotNil() predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotNull(FieldWalletRequests))
}

// AvgAccountCostEQ applies the EQ predicate on the "avg_account_cost" field.
func AvgAccountCostEQ(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAvgAccountCost, v))
}

// AvgAccountCostNEQ applies the NEQ predicate on the "avg_account_cost" field.
func AvgAccountCostNEQ(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldAvgAccountCost, v))
}

// AvgAccountCostIn applies the In predicate on the "avg_account_cost" field.
func AvgAccountCostIn(vs ...float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldAvgAccountCost, vs...))
}

// AvgAccountCostNotIn applies the NotIn predicate on the "avg_account_cost" field.
func AvgAccountCostNotIn(vs ...float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldAvgAccountCost, vs...))
}

// AvgAccountCostGT applies the GT predicate on the "avg_account_cost" field.
func AvgAccountCostGT(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldAvgAccountCost, v))
}

// AvgAccountCostGTE applies the GTE predicate on the "avg_account_cost" field.
func AvgAccountCostGTE(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldAvgAccountCost, v))
}

// AvgAccountCostLT applies the LT predicate on the "avg_account_cost" field.
func AvgAccountCostLT(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldAvgAccountCost, v))
}

// AvgAccountCostLTE applies the LTE predicate on the "avg_account_cost" field.
func AvgAccountCostLTE(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldAvgAccountCost, v))
}

// AvgActualCostEQ applies the EQ predicate on the "avg_actual_cost" field.
func AvgActualCostEQ(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAvgActualCost, v))
}

// AvgActualCostNEQ applies the NEQ predicate on the "avg_actual_cost" field.
func AvgActualCostNEQ(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldAvgActualCost, v))
}

// AvgActualCostIn applies the In predicate on the "avg_actual_cost" field.
func AvgActualCostIn(vs ...float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldAvgActualCost, vs...))
}

// AvgActualCostNotIn applies the NotIn predicate on the "avg_actual_cost" field.
func AvgActualCostNotIn(vs ...float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldAvgActualCost, vs...))
}

// AvgActualCostGT applies the GT predicate on the "avg_actual_cost" field.
func AvgActualCostGT(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldAvgActualCost, v))
}

// AvgActualCostGTE applies the GTE predicate on the "avg_actual_cost" field.
func AvgActualCostGTE(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldAvgActualCost, v))
}

// AvgActualCostLT applies the LT predicate on the "avg_actual_cost" field.
func AvgActualCostLT(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldAvgActualCost, v))
}

// AvgActualCostLTE applies the LTE predicate on the "avg_actual_cost" field.
func AvgActualCostLTE(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldAvgActualCost, v))
}

// AccountRemainingEQ applies the EQ predicate on the "account_remaining" field.
func AccountRemainingEQ(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAccountRemaining, v))
}

// AccountRemainingNEQ applies the NEQ predicate on the "account_remaining" field.
func AccountRemainingNEQ(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldAccountRemaining, v))
}

// AccountRemainingIn applies the In predicate on the "account_remaining" field.
func AccountRemainingIn(vs ...float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldAccountRemaining, vs...))
}

// AccountRemainingNotIn applies the NotIn predicate on the "account_remaining" field.
func AccountRemainingNotIn(vs ...float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldAccountRemaining, vs...))
}

// AccountRemainingGT applies the GT predicate on the "account_remaining" field.
func AccountRemainingGT(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldAccountRemaining, v))
}

// AccountRemainingGTE applies the GTE predicate on the "account_remaining" field.
func AccountRemainingGTE(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldAccountRemaining, v))
}

// AccountRemainingLT applies the LT predicate on the "account_remaining" field.
func AccountRemainingLT(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldAccountRemaining, v))
}

// AccountRemainingLTE applies the LTE predicate on the "account_remaining" field.
func AccountRemainingLTE(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldAccountRemaining, v))
}

// AccountRemainingIsNil applies the IsNil predicate on the "account_remaining" field.
func AccountRemainingIsNil() predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIsNull(FieldAccountRemaining))
}

// AccountRemainingNotNil applies the NotNil predicate on the "account_remaining" field.
func AccountRemainingNotNil() predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotNull(FieldAccountRemaining))
}

// APIKeyRemainingEQ applies the EQ predicate on the "api_key_remaining" field.
func APIKeyRemainingEQ(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldAPIKeyRemaining, v))
}

// APIKeyRemainingNEQ applies the NEQ predicate on the "api_key_remaining" field.
func APIKeyRemainingNEQ(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldAPIKeyRemaining, v))
}

// APIKeyRemainingIn applies the In predicate on the "api_key_remaining" field.
func APIKeyRemainingIn(vs ...float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldAPIKeyRemaining, vs...))
}

// APIKeyRemainingNotIn applies the NotIn predicate on the "api_key_remaining" field.
func APIKeyRemainingNotIn(vs ...float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldAPIKeyRemaining, vs...))
}

// APIKeyRemainingGT applies the GT predicate on the "api_key_remaining" field.
func APIKeyRemainingGT(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldAPIKeyRemaining, v))
}

// APIKeyRemainingGTE applies the GTE predicate on the "api_key_remaining" field.
func APIKeyRemainingGTE(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldAPIKeyRemaining, v))
}

// APIKeyRemainingLT applies the LT predicate on the "api_key_remaining" field.
func APIKeyRemainingLT(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldAPIKeyRemaining, v))
}

// APIKeyRemainingLTE applies the LTE predicate on the "api_key_remaining" field.
func APIKeyRemainingLTE(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldAPIKeyRemaining, v))
}

// APIKeyRemainingIsNil applies the IsNil predicate on the "api_key_remaining" field.
func APIKeyRemainingIsNil() predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIsNull(FieldAPIKeyRemaining))
}

// APIKeyRemainingNotNil applies the NotNil predicate on the "api_key_remaining" field.
func APIKeyRemainingNotNil() predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotNull(FieldAPIKeyRemaining))
}

// WalletRemainingEQ applies the EQ predicate on the "wallet_remaining" field.
func WalletRemainingEQ(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldWalletRemaining, v))
}

// WalletRemainingNEQ applies the NEQ predicate on the "wallet_remaining" field.
func WalletRemainingNEQ(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldWalletRemaining, v))
}

// WalletRemainingIn applies the In predicate on the "wallet_remaining" field.
func WalletRemainingIn(vs ...float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldWalletRemaining, vs...))
}

// WalletRemainingNotIn applies the NotIn predicate on the "wallet_remaining" field.
func WalletRemainingNotIn(vs ...float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldWalletRemaining, vs...))
}

// WalletRemainingGT applies the GT predicate on the "wallet_remaining" field.
func WalletRemainingGT(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldWalletRemaining, v))
}

// WalletRemainingGTE applies the GTE predicate on the "wallet_remaining" field.
func WalletRemainingGTE(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldWalletRemaining, v))
}

// WalletRemainingLT applies the LT predicate on the "wallet_remaining" field.
func WalletRemainingLT(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldWalletRemaining, v))
}

// WalletRemainingLTE applies the LTE predicate on the "wallet_remaining" field.
func WalletRemainingLTE(v float64) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldWalletRemaining, v))
}

// WalletRemainingIsNil applies the IsNil predicate on the "wallet_remaining" field.
func WalletRemainingIsNil() predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIsNull(FieldWalletRemaining))
}

// WalletRemainingNotNil applies the NotNil predicate on the "wallet_remaining" field.
func WalletRemainingNotNil() predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotNull(FieldWalletRemaining))
}

// SampleCountEQ applies the EQ predicate on the "sample_count" field.
func SampleCountEQ(v int) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldSampleCount, v))
}

// SampleCountNEQ applies the NEQ predicate on the "sample_count" field.
func SampleCountNEQ(v int) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldSampleCount, v))
}

// SampleCountIn applies the In predicate on the "sample_count" field.
func SampleCountIn(vs ...int) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldSampleCount, vs...))
}

// SampleCountNotIn applies the NotIn predicate on the "sample_count" field.
func SampleCountNotIn(vs ...int) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldSampleCount, vs...))
}

// SampleCountGT applies the GT predicate on the "sample_count" field.
func SampleCountGT(v int) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldSampleCount, v))
}

// SampleCountGTE applies the GTE predicate on the "sample_count" field.
func SampleCountGTE(v int) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldSampleCount, v))
}

// SampleCountLT applies the LT predicate on the "sample_count" field.
func SampleCountLT(v int) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldSampleCount, v))
}

// SampleCountLTE applies the LTE predicate on the "sample_count" field.
func SampleCountLTE(v int) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldSampleCount, v))
}

// BottleneckEQ applies the EQ predicate on the "bottleneck" field.
func BottleneckEQ(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldBottleneck, v))
}

// BottleneckNEQ applies the NEQ predicate on the "bottleneck" field.
func BottleneckNEQ(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldBottleneck, v))
}

// BottleneckIn applies the In predicate on the "bottleneck" field.
func BottleneckIn(vs ...string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldBottleneck, vs...))
}

// BottleneckNotIn applies the NotIn predicate on the "bottleneck" field.
func BottleneckNotIn(vs ...string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldBottleneck, vs...))
}

// BottleneckGT applies the GT predicate on the "bottleneck" field.
func BottleneckGT(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldBottleneck, v))
}

// BottleneckGTE applies the GTE predicate on the "bottleneck" field.
func BottleneckGTE(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldBottleneck, v))
}

// BottleneckLT applies the LT predicate on the "bottleneck" field.
func BottleneckLT(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldBottleneck, v))
}

// BottleneckLTE applies the LTE predicate on the "bottleneck" field.
func BottleneckLTE(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldBottleneck, v))
}

// BottleneckContains applies the Contains predicate on the "bottleneck" field.
func BottleneckContains(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldContains(FieldBottleneck, v))
}

// BottleneckHasPrefix applies the HasPrefix predicate on the "bottleneck" field.
func BottleneckHasPrefix(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldHasPrefix(FieldBottleneck, v))
}

// BottleneckHasSuffix applies the HasSuffix predicate on the "bottleneck" field.
func BottleneckHasSuffix(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldHasSuffix(FieldBottleneck, v))
}

// BottleneckEqualFold applies the EqualFold predicate on the "bottleneck" field.
func BottleneckEqualFold(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEqualFold(FieldBottleneck, v))
}

// BottleneckContainsFold applies the ContainsFold predicate on the "bottleneck" field.
func BottleneckContainsFold(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldContainsFold(FieldBottleneck, v))
}

// QqbotAppIDEQ applies the EQ predicate on the "qqbot_app_id" field.
func QqbotAppIDEQ(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldQqbotAppID, v))
}

// QqbotAppIDNEQ applies the NEQ predicate on the "qqbot_app_id" field.
func QqbotAppIDNEQ(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldQqbotAppID, v))
}

// QqbotAppIDIn applies the In predicate on the "qqbot_app_id" field.
func QqbotAppIDIn(vs ...string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldQqbotAppID, vs...))
}

// QqbotAppIDNotIn applies the NotIn predicate on the "qqbot_app_id" field.
func QqbotAppIDNotIn(vs ...string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldQqbotAppID, vs...))
}

// QqbotAppIDGT applies the GT predicate on the "qqbot_app_id" field.
func QqbotAppIDGT(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldQqbotAppID, v))
}

// QqbotAppIDGTE applies the GTE predicate on the "qqbot_app_id" field.
func QqbotAppIDGTE(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldQqbotAppID, v))
}

// QqbotAppIDLT applies the LT predicate on the "qqbot_app_id" field.
func QqbotAppIDLT(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldQqbotAppID, v))
}

// QqbotAppIDLTE applies the LTE predicate on the "qqbot_app_id" field.
func QqbotAppIDLTE(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldQqbotAppID, v))
}

// QqbotAppIDContains applies the Contains predicate on the "qqbot_app_id" field.
func QqbotAppIDContains(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldContains(FieldQqbotAppID, v))
}

// QqbotAppIDHasPrefix applies the HasPrefix predicate on the "qqbot_app_id" field.
func QqbotAppIDHasPrefix(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldHasPrefix(FieldQqbotAppID, v))
}

// QqbotAppIDHasSuffix applies the HasSuffix predicate on the "qqbot_app_id" field.
func QqbotAppIDHasSuffix(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldHasSuffix(FieldQqbotAppID, v))
}

// QqbotAppIDEqualFold applies the EqualFold predicate on the "qqbot_app_id" field.
func QqbotAppIDEqualFold(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEqualFold(FieldQqbotAppID, v))
}

// QqbotAppIDContainsFold applies the ContainsFold predicate on the "qqbot_app_id" field.
func QqbotAppIDContainsFold(v string) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldContainsFold(FieldQqbotAppID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PoolCapacityAlertEvent) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PoolCapacityAlertEvent) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PoolCapacityAlertEvent) predicate.PoolCapacityAlertEvent {
	return predicate.PoolCapacityAlertEvent(sql.NotPredicates(p))
}
