server {
    listen 80;
    listen [::]:80;
    server_name qqbot.poke2api.com;

    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        root /var/www/letsencrypt;
    }

    location = /api/v1/public/qqbot/channel-status.png {
        access_log off;
        return 308 https://qqbot.mcwar.cn/api/v1/public/qqbot/channel-status.png$is_args$args;
    }

    location / {
        return 308 https://qqbot.mcwar.cn$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    server_name qqbot.poke2api.com;

    ssl_certificate /etc/nginx/certs/qqbot.poke2api.com_cert.pem;
    ssl_certificate_key /etc/nginx/certs/qqbot.poke2api.com_key.pem;

    location = /api/v1/public/qqbot/channel-status.png {
        access_log off;
        return 308 https://qqbot.mcwar.cn/api/v1/public/qqbot/channel-status.png$is_args$args;
    }

    location / {
        return 308 https://qqbot.mcwar.cn$request_uri;
    }
}
