// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcementemailjob"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AnnouncementEmailJobDelete is the builder for deleting a AnnouncementEmailJob entity.
type AnnouncementEmailJobDelete struct {
	config
	hooks    []Hook
	mutation *AnnouncementEmailJobMutation
}

// Where appends a list predicates to the AnnouncementEmailJobDelete builder.
func (_d *AnnouncementEmailJobDelete) Where(ps ...predicate.AnnouncementEmailJob) *AnnouncementEmailJobDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AnnouncementEmailJobDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AnnouncementEmailJobDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AnnouncementEmailJobDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(announcementemailjob.Table, sqlgraph.NewFieldSpec(announcementemailjob.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AnnouncementEmailJobDeleteOne is the builder for deleting a single AnnouncementEmailJob entity.
type AnnouncementEmailJobDeleteOne struct {
	_d *AnnouncementEmailJobDelete
}

// Where appends a list predicates to the AnnouncementEmailJobDelete builder.
func (_d *AnnouncementEmailJobDeleteOne) Where(ps ...predicate.AnnouncementEmailJob) *AnnouncementEmailJobDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AnnouncementEmailJobDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{announcementemailjob.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AnnouncementEmailJobDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
