// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/poolcapacityalertdelivery"
)

// PoolCapacityAlertDelivery is the model entity for the PoolCapacityAlertDelivery schema.
type PoolCapacityAlertDelivery struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// EventID holds the value of the "event_id" field.
	EventID int64 `json:"event_id,omitempty"`
	// Channel holds the value of the "channel" field.
	Channel string `json:"channel,omitempty"`
	// RecipientUserID holds the value of the "recipient_user_id" field.
	RecipientUserID int64 `json:"recipient_user_id,omitempty"`
	// IdentityChannelID holds the value of the "identity_channel_id" field.
	IdentityChannelID int64 `json:"identity_channel_id,omitempty"`
	// RecipientEmail holds the value of the "recipient_email" field.
	RecipientEmail string `json:"recipient_email,omitempty"`
	// RecipientName holds the value of the "recipient_name" field.
	RecipientName string `json:"recipient_name,omitempty"`
	// Locale holds the value of the "locale" field.
	Locale string `json:"locale,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AttemptCount holds the value of the "attempt_count" field.
	AttemptCount int `json:"attempt_count,omitempty"`
	// MaxAttempts holds the value of the "max_attempts" field.
	MaxAttempts int `json:"max_attempts,omitempty"`
	// NextAttemptAt holds the value of the "next_attempt_at" field.
	NextAttemptAt time.Time `json:"next_attempt_at,omitempty"`
	// LeaseOwner holds the value of the "lease_owner" field.
	LeaseOwner *string `json:"lease_owner,omitempty"`
	// LeaseExpiresAt holds the value of the "lease_expires_at" field.
	LeaseExpiresAt *time.Time `json:"lease_expires_at,omitempty"`
	// LastErrorClass holds the value of the "last_error_class" field.
	LastErrorClass *string `json:"last_error_class,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// SentAt holds the value of the "sent_at" field.
	SentAt *time.Time `json:"sent_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PoolCapacityAlertDelivery) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case poolcapacityalertdelivery.FieldID, poolcapacityalertdelivery.FieldEventID, poolcapacityalertdelivery.FieldRecipientUserID, poolcapacityalertdelivery.FieldIdentityChannelID, poolcapacityalertdelivery.FieldAttemptCount, poolcapacityalertdelivery.FieldMaxAttempts:
			values[i] = new(sql.NullInt64)
		case poolcapacityalertdelivery.FieldChannel, poolcapacityalertdelivery.FieldRecipientEmail, poolcapacityalertdelivery.FieldRecipientName, poolcapacityalertdelivery.FieldLocale, poolcapacityalertdelivery.FieldStatus, poolcapacityalertdelivery.FieldLeaseOwner, poolcapacityalertdelivery.FieldLastErrorClass, poolcapacityalertdelivery.FieldLastError:
			values[i] = new(sql.NullString)
		case poolcapacityalertdelivery.FieldNextAttemptAt, poolcapacityalertdelivery.FieldLeaseExpiresAt, poolcapacityalertdelivery.FieldSentAt, poolcapacityalertdelivery.FieldCreatedAt, poolcapacityalertdelivery.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PoolCapacityAlertDelivery fields.
func (_m *PoolCapacityAlertDelivery) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case poolcapacityalertdelivery.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case poolcapacityalertdelivery.FieldEventID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field event_id", values[i])
			} else if value.Valid {
				_m.EventID = value.Int64
			}
		case poolcapacityalertdelivery.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				_m.Channel = value.String
			}
		case poolcapacityalertdelivery.FieldRecipientUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field recipient_user_id", values[i])
			} else if value.Valid {
				_m.RecipientUserID = value.Int64
			}
		case poolcapacityalertdelivery.FieldIdentityChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field identity_channel_id", values[i])
			} else if value.Valid {
				_m.IdentityChannelID = value.Int64
			}
		case poolcapacityalertdelivery.FieldRecipientEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient_email", values[i])
			} else if value.Valid {
				_m.RecipientEmail = value.String
			}
		case poolcapacityalertdelivery.FieldRecipientName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient_name", values[i])
			} else if value.Valid {
				_m.RecipientName = value.String
			}
		case poolcapacityalertdelivery.FieldLocale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locale", values[i])
			} else if value.Valid {
				_m.Locale = value.String
			}
		case poolcapacityalertdelivery.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case poolcapacityalertdelivery.FieldAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_count", values[i])
			} else if value.Valid {
				_m.AttemptCount = int(value.Int64)
			}
		case poolcapacityalertdelivery.FieldMaxAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_attempts", values[i])
			} else if value.Valid {
				_m.MaxAttempts = int(value.Int64)
			}
		case poolcapacityalertdelivery.FieldNextAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_attempt_at", values[i])
			} else if value.Valid {
				_m.NextAttemptAt = value.Time
			}
		case poolcapacityalertdelivery.FieldLeaseOwner:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lease_owner", values[i])
			} else if value.Valid {
				_m.LeaseOwner = new(string)
				*_m.LeaseOwner = value.String
			}
		case poolcapacityalertdelivery.FieldLeaseExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field lease_expires_at", values[i])
			} else if value.Valid {
				_m.LeaseExpiresAt = new(time.Time)
				*_m.LeaseExpiresAt = value.Time
			}
		case poolcapacityalertdelivery.FieldLastErrorClass:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_class", values[i])
			} else if value.Valid {
				_m.LastErrorClass = new(string)
				*_m.LastErrorClass = value.String
			}
		case poolcapacityalertdelivery.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case poolcapacityalertdelivery.FieldSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sent_at", values[i])
			} else if value.Valid {
				_m.SentAt = new(time.Time)
				*_m.SentAt = value.Time
			}
		case poolcapacityalertdelivery.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case poolcapacityalertdelivery.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PoolCapacityAlertDelivery.
// This includes values selected through modifiers, order, etc.
func (_m *PoolCapacityAlertDelivery) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PoolCapacityAlertDelivery.
// Note that you need to call PoolCapacityAlertDelivery.Unwrap() before calling this method if this PoolCapacityAlertDelivery
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PoolCapacityAlertDelivery) Update() *PoolCapacityAlertDeliveryUpdateOne {
	return NewPoolCapacityAlertDeliveryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PoolCapacityAlertDelivery entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PoolCapacityAlertDelivery) Unwrap() *PoolCapacityAlertDelivery {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PoolCapacityAlertDelivery is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PoolCapacityAlertDelivery) String() string {
	var builder strings.Builder
	builder.WriteString("PoolCapacityAlertDelivery(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("event_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EventID))
	builder.WriteString(", ")
	builder.WriteString("channel=")
	builder.WriteString(_m.Channel)
	builder.WriteString(", ")
	builder.WriteString("recipient_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecipientUserID))
	builder.WriteString(", ")
	builder.WriteString("identity_channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.IdentityChannelID))
	builder.WriteString(", ")
	builder.WriteString("recipient_email=")
	builder.WriteString(_m.RecipientEmail)
	builder.WriteString(", ")
	builder.WriteString("recipient_name=")
	builder.WriteString(_m.RecipientName)
	builder.WriteString(", ")
	builder.WriteString("locale=")
	builder.WriteString(_m.Locale)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptCount))
	builder.WriteString(", ")
	builder.WriteString("max_attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxAttempts))
	builder.WriteString(", ")
	builder.WriteString("next_attempt_at=")
	builder.WriteString(_m.NextAttemptAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LeaseOwner; v != nil {
		builder.WriteString("lease_owner=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LeaseExpiresAt; v != nil {
		builder.WriteString("lease_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastErrorClass; v != nil {
		builder.WriteString("last_error_class=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SentAt; v != nil {
		builder.WriteString("sent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PoolCapacityAlertDeliveries is a parsable slice of PoolCapacityAlertDelivery.
type PoolCapacityAlertDeliveries []*PoolCapacityAlertDelivery
