// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/poolcapacityalertevent"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PoolCapacityAlertEventDelete is the builder for deleting a PoolCapacityAlertEvent entity.
type PoolCapacityAlertEventDelete struct {
	config
	hooks    []Hook
	mutation *PoolCapacityAlertEventMutation
}

// Where appends a list predicates to the PoolCapacityAlertEventDelete builder.
func (_d *PoolCapacityAlertEventDelete) Where(ps ...predicate.PoolCapacityAlertEvent) *PoolCapacityAlertEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PoolCapacityAlertEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PoolCapacityAlertEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PoolCapacityAlertEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(poolcapacityalertevent.Table, sqlgraph.NewFieldSpec(poolcapacityalertevent.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PoolCapacityAlertEventDeleteOne is the builder for deleting a single PoolCapacityAlertEvent entity.
type PoolCapacityAlertEventDeleteOne struct {
	_d *PoolCapacityAlertEventDelete
}

// Where appends a list predicates to the PoolCapacityAlertEventDelete builder.
func (_d *PoolCapacityAlertEventDeleteOne) Where(ps ...predicate.PoolCapacityAlertEvent) *PoolCapacityAlertEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PoolCapacityAlertEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{poolcapacityalertevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PoolCapacityAlertEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
