// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/poolcapacityalertdelivery"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PoolCapacityAlertDeliveryUpdate is the builder for updating PoolCapacityAlertDelivery entities.
type PoolCapacityAlertDeliveryUpdate struct {
	config
	hooks    []Hook
	mutation *PoolCapacityAlertDeliveryMutation
}

// Where appends a list predicates to the PoolCapacityAlertDeliveryUpdate builder.
func (_u *PoolCapacityAlertDeliveryUpdate) Where(ps ...predicate.PoolCapacityAlertDelivery) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetEventID(v int64) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.ResetEventID()
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNillableEventID(v *int64) *PoolCapacityAlertDeliveryUpdate {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// AddEventID adds value to the "event_id" field.
func (_u *PoolCapacityAlertDeliveryUpdate) AddEventID(v int64) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.AddEventID(v)
	return _u
}

// SetChannel sets the "channel" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetChannel(v string) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNillableChannel(v *string) *PoolCapacityAlertDeliveryUpdate {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetRecipientUserID sets the "recipient_user_id" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetRecipientUserID(v int64) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.ResetRecipientUserID()
	_u.mutation.SetRecipientUserID(v)
	return _u
}

// SetNillableRecipientUserID sets the "recipient_user_id" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNillableRecipientUserID(v *int64) *PoolCapacityAlertDeliveryUpdate {
	if v != nil {
		_u.SetRecipientUserID(*v)
	}
	return _u
}

// AddRecipientUserID adds value to the "recipient_user_id" field.
func (_u *PoolCapacityAlertDeliveryUpdate) AddRecipientUserID(v int64) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.AddRecipientUserID(v)
	return _u
}

// SetIdentityChannelID sets the "identity_channel_id" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetIdentityChannelID(v int64) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.ResetIdentityChannelID()
	_u.mutation.SetIdentityChannelID(v)
	return _u
}

// SetNillableIdentityChannelID sets the "identity_channel_id" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNillableIdentityChannelID(v *int64) *PoolCapacityAlertDeliveryUpdate {
	if v != nil {
		_u.SetIdentityChannelID(*v)
	}
	return _u
}

// AddIdentityChannelID adds value to the "identity_channel_id" field.
func (_u *PoolCapacityAlertDeliveryUpdate) AddIdentityChannelID(v int64) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.AddIdentityChannelID(v)
	return _u
}

// SetRecipientEmail sets the "recipient_email" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetRecipientEmail(v string) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.SetRecipientEmail(v)
	return _u
}

// SetNillableRecipientEmail sets the "recipient_email" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNillableRecipientEmail(v *string) *PoolCapacityAlertDeliveryUpdate {
	if v != nil {
		_u.SetRecipientEmail(*v)
	}
	return _u
}

// SetRecipientName sets the "recipient_name" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetRecipientName(v string) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.SetRecipientName(v)
	return _u
}

// SetNillableRecipientName sets the "recipient_name" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNillableRecipientName(v *string) *PoolCapacityAlertDeliveryUpdate {
	if v != nil {
		_u.SetRecipientName(*v)
	}
	return _u
}

// SetLocale sets the "locale" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetLocale(v string) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.SetLocale(v)
	return _u
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNillableLocale(v *string) *PoolCapacityAlertDeliveryUpdate {
	if v != nil {
		_u.SetLocale(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetStatus(v string) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNillableStatus(v *string) *PoolCapacityAlertDeliveryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetAttemptCount(v int) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNillableAttemptCount(v *int) *PoolCapacityAlertDeliveryUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *PoolCapacityAlertDeliveryUpdate) AddAttemptCount(v int) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetMaxAttempts(v int) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNillableMaxAttempts(v *int) *PoolCapacityAlertDeliveryUpdate {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *PoolCapacityAlertDeliveryUpdate) AddMaxAttempts(v int) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNextAttemptAt(v time.Time) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNillableNextAttemptAt(v *time.Time) *PoolCapacityAlertDeliveryUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetLeaseOwner(v string) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNillableLeaseOwner(v *string) *PoolCapacityAlertDeliveryUpdate {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (_u *PoolCapacityAlertDeliveryUpdate) ClearLeaseOwner() *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.ClearLeaseOwner()
	return _u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetLeaseExpiresAt(v time.Time) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.SetLeaseExpiresAt(v)
	return _u
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNillableLeaseExpiresAt(v *time.Time) *PoolCapacityAlertDeliveryUpdate {
	if v != nil {
		_u.SetLeaseExpiresAt(*v)
	}
	return _u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (_u *PoolCapacityAlertDeliveryUpdate) ClearLeaseExpiresAt() *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.ClearLeaseExpiresAt()
	return _u
}

// SetLastErrorClass sets the "last_error_class" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetLastErrorClass(v string) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.SetLastErrorClass(v)
	return _u
}

// SetNillableLastErrorClass sets the "last_error_class" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNillableLastErrorClass(v *string) *PoolCapacityAlertDeliveryUpdate {
	if v != nil {
		_u.SetLastErrorClass(*v)
	}
	return _u
}

// ClearLastErrorClass clears the value of the "last_error_class" field.
func (_u *PoolCapacityAlertDeliveryUpdate) ClearLastErrorClass() *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.ClearLastErrorClass()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetLastError(v string) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNillableLastError(v *string) *PoolCapacityAlertDeliveryUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *PoolCapacityAlertDeliveryUpdate) ClearLastError() *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetSentAt(v time.Time) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdate) SetNillableSentAt(v *time.Time) *PoolCapacityAlertDeliveryUpdate {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *PoolCapacityAlertDeliveryUpdate) ClearSentAt() *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.ClearSentAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PoolCapacityAlertDeliveryUpdate) SetUpdatedAt(v time.Time) *PoolCapacityAlertDeliveryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PoolCapacityAlertDeliveryMutation object of the builder.
func (_u *PoolCapacityAlertDeliveryUpdate) Mutation() *PoolCapacityAlertDeliveryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PoolCapacityAlertDeliveryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PoolCapacityAlertDeliveryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PoolCapacityAlertDeliveryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PoolCapacityAlertDeliveryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PoolCapacityAlertDeliveryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := poolcapacityalertdelivery.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PoolCapacityAlertDeliveryUpdate) check() error {
	if v, ok := _u.mutation.Channel(); ok {
		if err := poolcapacityalertdelivery.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "PoolCapacityAlertDelivery.channel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecipientEmail(); ok {
		if err := poolcapacityalertdelivery.RecipientEmailValidator(v); err != nil {
			return &ValidationError{Name: "recipient_email", err: fmt.Errorf(`ent: validator failed for field "PoolCapacityAlertDelivery.recipient_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecipientName(); ok {
		if err := poolcapacityalertdelivery.RecipientNameValidator(v); err != nil {
			return &ValidationError{Name: "recipient_name", err: fmt.Errorf(`ent: validator failed for field "PoolCapacityAlertDelivery.recipient_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Locale(); ok {
		if err := poolcapacityalertdelivery.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "locale", err: fmt.Errorf(`ent: validator failed for field "PoolCapacityAlertDelivery.locale": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := poolcapacityalertdelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PoolCapacityAlertDelivery.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseOwner(); ok {
		if err := poolcapacityalertdelivery.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "PoolCapacityAlertDelivery.lease_owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorClass(); ok {
		if err := poolcapacityalertdelivery.LastErrorClassValidator(v); err != nil {
			return &ValidationError{Name: "last_error_class", err: fmt.Errorf(`ent: validator failed for field "PoolCapacityAlertDelivery.last_error_class": %w`, err)}
		}
	}
	return nil
}

func (_u *PoolCapacityAlertDeliveryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(poolcapacityalertdelivery.Table, poolcapacityalertdelivery.Columns, sqlgraph.NewFieldSpec(poolcapacityalertdelivery.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldEventID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEventID(); ok {
		_spec.AddField(poolcapacityalertdelivery.FieldEventID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecipientUserID(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldRecipientUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecipientUserID(); ok {
		_spec.AddField(poolcapacityalertdelivery.FieldRecipientUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IdentityChannelID(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldIdentityChannelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedIdentityChannelID(); ok {
		_spec.AddField(poolcapacityalertdelivery.FieldIdentityChannelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RecipientEmail(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldRecipientEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecipientName(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldRecipientName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Locale(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldLocale, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(poolcapacityalertdelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(poolcapacityalertdelivery.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldNextAttemptAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldLeaseOwner, field.TypeString, value)
	}
	if _u.mutation.LeaseOwnerCleared() {
		_spec.ClearField(poolcapacityalertdelivery.FieldLeaseOwner, field.TypeString)
	}
	if value, ok := _u.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldLeaseExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.LeaseExpiresAtCleared() {
		_spec.ClearField(poolcapacityalertdelivery.FieldLeaseExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastErrorClass(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldLastErrorClass, field.TypeString, value)
	}
	if _u.mutation.LastErrorClassCleared() {
		_spec.ClearField(poolcapacityalertdelivery.FieldLastErrorClass, field.TypeString)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(poolcapacityalertdelivery.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(poolcapacityalertdelivery.FieldSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{poolcapacityalertdelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PoolCapacityAlertDeliveryUpdateOne is the builder for updating a single PoolCapacityAlertDelivery entity.
type PoolCapacityAlertDeliveryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PoolCapacityAlertDeliveryMutation
}

// SetEventID sets the "event_id" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetEventID(v int64) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.ResetEventID()
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNillableEventID(v *int64) *PoolCapacityAlertDeliveryUpdateOne {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// AddEventID adds value to the "event_id" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) AddEventID(v int64) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.AddEventID(v)
	return _u
}

// SetChannel sets the "channel" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetChannel(v string) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNillableChannel(v *string) *PoolCapacityAlertDeliveryUpdateOne {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetRecipientUserID sets the "recipient_user_id" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetRecipientUserID(v int64) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.ResetRecipientUserID()
	_u.mutation.SetRecipientUserID(v)
	return _u
}

// SetNillableRecipientUserID sets the "recipient_user_id" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNillableRecipientUserID(v *int64) *PoolCapacityAlertDeliveryUpdateOne {
	if v != nil {
		_u.SetRecipientUserID(*v)
	}
	return _u
}

// AddRecipientUserID adds value to the "recipient_user_id" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) AddRecipientUserID(v int64) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.AddRecipientUserID(v)
	return _u
}

// SetIdentityChannelID sets the "identity_channel_id" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetIdentityChannelID(v int64) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.ResetIdentityChannelID()
	_u.mutation.SetIdentityChannelID(v)
	return _u
}

// SetNillableIdentityChannelID sets the "identity_channel_id" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNillableIdentityChannelID(v *int64) *PoolCapacityAlertDeliveryUpdateOne {
	if v != nil {
		_u.SetIdentityChannelID(*v)
	}
	return _u
}

// AddIdentityChannelID adds value to the "identity_channel_id" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) AddIdentityChannelID(v int64) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.AddIdentityChannelID(v)
	return _u
}

// SetRecipientEmail sets the "recipient_email" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetRecipientEmail(v string) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.SetRecipientEmail(v)
	return _u
}

// SetNillableRecipientEmail sets the "recipient_email" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNillableRecipientEmail(v *string) *PoolCapacityAlertDeliveryUpdateOne {
	if v != nil {
		_u.SetRecipientEmail(*v)
	}
	return _u
}

// SetRecipientName sets the "recipient_name" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetRecipientName(v string) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.SetRecipientName(v)
	return _u
}

// SetNillableRecipientName sets the "recipient_name" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNillableRecipientName(v *string) *PoolCapacityAlertDeliveryUpdateOne {
	if v != nil {
		_u.SetRecipientName(*v)
	}
	return _u
}

// SetLocale sets the "locale" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetLocale(v string) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.SetLocale(v)
	return _u
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNillableLocale(v *string) *PoolCapacityAlertDeliveryUpdateOne {
	if v != nil {
		_u.SetLocale(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetStatus(v string) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNillableStatus(v *string) *PoolCapacityAlertDeliveryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetAttemptCount(v int) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNillableAttemptCount(v *int) *PoolCapacityAlertDeliveryUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) AddAttemptCount(v int) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetMaxAttempts(v int) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNillableMaxAttempts(v *int) *PoolCapacityAlertDeliveryUpdateOne {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) AddMaxAttempts(v int) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNextAttemptAt(v time.Time) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNillableNextAttemptAt(v *time.Time) *PoolCapacityAlertDeliveryUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetLeaseOwner(v string) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNillableLeaseOwner(v *string) *PoolCapacityAlertDeliveryUpdateOne {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) ClearLeaseOwner() *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.ClearLeaseOwner()
	return _u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetLeaseExpiresAt(v time.Time) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.SetLeaseExpiresAt(v)
	return _u
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNillableLeaseExpiresAt(v *time.Time) *PoolCapacityAlertDeliveryUpdateOne {
	if v != nil {
		_u.SetLeaseExpiresAt(*v)
	}
	return _u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) ClearLeaseExpiresAt() *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.ClearLeaseExpiresAt()
	return _u
}

// SetLastErrorClass sets the "last_error_class" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetLastErrorClass(v string) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.SetLastErrorClass(v)
	return _u
}

// SetNillableLastErrorClass sets the "last_error_class" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNillableLastErrorClass(v *string) *PoolCapacityAlertDeliveryUpdateOne {
	if v != nil {
		_u.SetLastErrorClass(*v)
	}
	return _u
}

// ClearLastErrorClass clears the value of the "last_error_class" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) ClearLastErrorClass() *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.ClearLastErrorClass()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetLastError(v string) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNillableLastError(v *string) *PoolCapacityAlertDeliveryUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) ClearLastError() *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetSentAt(v time.Time) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetNillableSentAt(v *time.Time) *PoolCapacityAlertDeliveryUpdateOne {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) ClearSentAt() *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.ClearSentAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SetUpdatedAt(v time.Time) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PoolCapacityAlertDeliveryMutation object of the builder.
func (_u *PoolCapacityAlertDeliveryUpdateOne) Mutation() *PoolCapacityAlertDeliveryMutation {
	return _u.mutation
}

// Where appends a list predicates to the PoolCapacityAlertDeliveryUpdate builder.
func (_u *PoolCapacityAlertDeliveryUpdateOne) Where(ps ...predicate.PoolCapacityAlertDelivery) *PoolCapacityAlertDeliveryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PoolCapacityAlertDeliveryUpdateOne) Select(field string, fields ...string) *PoolCapacityAlertDeliveryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PoolCapacityAlertDelivery entity.
func (_u *PoolCapacityAlertDeliveryUpdateOne) Save(ctx context.Context) (*PoolCapacityAlertDelivery, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PoolCapacityAlertDeliveryUpdateOne) SaveX(ctx context.Context) *PoolCapacityAlertDelivery {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PoolCapacityAlertDeliveryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PoolCapacityAlertDeliveryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PoolCapacityAlertDeliveryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := poolcapacityalertdelivery.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PoolCapacityAlertDeliveryUpdateOne) check() error {
	if v, ok := _u.mutation.Channel(); ok {
		if err := poolcapacityalertdelivery.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "PoolCapacityAlertDelivery.channel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecipientEmail(); ok {
		if err := poolcapacityalertdelivery.RecipientEmailValidator(v); err != nil {
			return &ValidationError{Name: "recipient_email", err: fmt.Errorf(`ent: validator failed for field "PoolCapacityAlertDelivery.recipient_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecipientName(); ok {
		if err := poolcapacityalertdelivery.RecipientNameValidator(v); err != nil {
			return &ValidationError{Name: "recipient_name", err: fmt.Errorf(`ent: validator failed for field "PoolCapacityAlertDelivery.recipient_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Locale(); ok {
		if err := poolcapacityalertdelivery.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "locale", err: fmt.Errorf(`ent: validator failed for field "PoolCapacityAlertDelivery.locale": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := poolcapacityalertdelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PoolCapacityAlertDelivery.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseOwner(); ok {
		if err := poolcapacityalertdelivery.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "PoolCapacityAlertDelivery.lease_owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorClass(); ok {
		if err := poolcapacityalertdelivery.LastErrorClassValidator(v); err != nil {
			return &ValidationError{Name: "last_error_class", err: fmt.Errorf(`ent: validator failed for field "PoolCapacityAlertDelivery.last_error_class": %w`, err)}
		}
	}
	return nil
}

func (_u *PoolCapacityAlertDeliveryUpdateOne) sqlSave(ctx context.Context) (_node *PoolCapacityAlertDelivery, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(poolcapacityalertdelivery.Table, poolcapacityalertdelivery.Columns, sqlgraph.NewFieldSpec(poolcapacityalertdelivery.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PoolCapacityAlertDelivery.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, poolcapacityalertdelivery.FieldID)
		for _, f := range fields {
			if !poolcapacityalertdelivery.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != poolcapacityalertdelivery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldEventID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEventID(); ok {
		_spec.AddField(poolcapacityalertdelivery.FieldEventID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecipientUserID(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldRecipientUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecipientUserID(); ok {
		_spec.AddField(poolcapacityalertdelivery.FieldRecipientUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IdentityChannelID(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldIdentityChannelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedIdentityChannelID(); ok {
		_spec.AddField(poolcapacityalertdelivery.FieldIdentityChannelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RecipientEmail(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldRecipientEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecipientName(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldRecipientName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Locale(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldLocale, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(poolcapacityalertdelivery.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(poolcapacityalertdelivery.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldNextAttemptAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldLeaseOwner, field.TypeString, value)
	}
	if _u.mutation.LeaseOwnerCleared() {
		_spec.ClearField(poolcapacityalertdelivery.FieldLeaseOwner, field.TypeString)
	}
	if value, ok := _u.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldLeaseExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.LeaseExpiresAtCleared() {
		_spec.ClearField(poolcapacityalertdelivery.FieldLeaseExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastErrorClass(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldLastErrorClass, field.TypeString, value)
	}
	if _u.mutation.LastErrorClassCleared() {
		_spec.ClearField(poolcapacityalertdelivery.FieldLastErrorClass, field.TypeString)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(poolcapacityalertdelivery.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(poolcapacityalertdelivery.FieldSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(poolcapacityalertdelivery.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PoolCapacityAlertDelivery{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{poolcapacityalertdelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
