// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/poolcapacityalertstate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PoolCapacityAlertStateDelete is the builder for deleting a PoolCapacityAlertState entity.
type PoolCapacityAlertStateDelete struct {
	config
	hooks    []Hook
	mutation *PoolCapacityAlertStateMutation
}

// Where appends a list predicates to the PoolCapacityAlertStateDelete builder.
func (_d *PoolCapacityAlertStateDelete) Where(ps ...predicate.PoolCapacityAlertState) *PoolCapacityAlertStateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PoolCapacityAlertStateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PoolCapacityAlertStateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PoolCapacityAlertStateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(poolcapacityalertstate.Table, sqlgraph.NewFieldSpec(poolcapacityalertstate.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PoolCapacityAlertStateDeleteOne is the builder for deleting a single PoolCapacityAlertState entity.
type PoolCapacityAlertStateDeleteOne struct {
	_d *PoolCapacityAlertStateDelete
}

// Where appends a list predicates to the PoolCapacityAlertStateDelete builder.
func (_d *PoolCapacityAlertStateDeleteOne) Where(ps ...predicate.PoolCapacityAlertState) *PoolCapacityAlertStateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PoolCapacityAlertStateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{poolcapacityalertstate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PoolCapacityAlertStateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
