// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/poolcapacityalertstate"
)

// PoolCapacityAlertState is the model entity for the PoolCapacityAlertState schema.
type PoolCapacityAlertState struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// GroupGeneration holds the value of the "group_generation" field.
	GroupGeneration int64 `json:"group_generation,omitempty"`
	// ScopeType holds the value of the "scope_type" field.
	ScopeType string `json:"scope_type,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *int64 `json:"account_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int64 `json:"api_key_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *int64 `json:"user_id,omitempty"`
	// BillingType holds the value of the "billing_type" field.
	BillingType *int8 `json:"billing_type,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Episode holds the value of the "episode" field.
	Episode int64 `json:"episode,omitempty"`
	// AlertMetric holds the value of the "alert_metric" field.
	AlertMetric string `json:"alert_metric,omitempty"`
	// PredictedRequests holds the value of the "predicted_requests" field.
	PredictedRequests *int64 `json:"predicted_requests,omitempty"`
	// RemainingBalanceUsd holds the value of the "remaining_balance_usd" field.
	RemainingBalanceUsd *float64 `json:"remaining_balance_usd,omitempty"`
	// PoolAuthoritativeBalanceUsd holds the value of the "pool_authoritative_balance_usd" field.
	PoolAuthoritativeBalanceUsd *float64 `json:"pool_authoritative_balance_usd,omitempty"`
	// NormalEstimatedBalanceUsd holds the value of the "normal_estimated_balance_usd" field.
	NormalEstimatedBalanceUsd *float64 `json:"normal_estimated_balance_usd,omitempty"`
	// PoolAccountCount holds the value of the "pool_account_count" field.
	PoolAccountCount int `json:"pool_account_count,omitempty"`
	// NormalAccountCount holds the value of the "normal_account_count" field.
	NormalAccountCount int `json:"normal_account_count,omitempty"`
	// SkippedAccountCount holds the value of the "skipped_account_count" field.
	SkippedAccountCount int `json:"skipped_account_count,omitempty"`
	// UnknownAccountCount holds the value of the "unknown_account_count" field.
	UnknownAccountCount int `json:"unknown_account_count,omitempty"`
	// StaleAccountCount holds the value of the "stale_account_count" field.
	StaleAccountCount int `json:"stale_account_count,omitempty"`
	// IncompatibleUnitAccountCount holds the value of the "incompatible_unit_account_count" field.
	IncompatibleUnitAccountCount int `json:"incompatible_unit_account_count,omitempty"`
	// ThresholdRequests holds the value of the "threshold_requests" field.
	ThresholdRequests int64 `json:"threshold_requests,omitempty"`
	// ThresholdUsd holds the value of the "threshold_usd" field.
	ThresholdUsd *float64 `json:"threshold_usd,omitempty"`
	// AccountRequests holds the value of the "account_requests" field.
	AccountRequests *int64 `json:"account_requests,omitempty"`
	// APIKeyRequests holds the value of the "api_key_requests" field.
	APIKeyRequests *int64 `json:"api_key_requests,omitempty"`
	// WalletRequests holds the value of the "wallet_requests" field.
	WalletRequests *int64 `json:"wallet_requests,omitempty"`
	// AvgAccountCost holds the value of the "avg_account_cost" field.
	AvgAccountCost float64 `json:"avg_account_cost,omitempty"`
	// AvgActualCost holds the value of the "avg_actual_cost" field.
	AvgActualCost float64 `json:"avg_actual_cost,omitempty"`
	// SampleCount holds the value of the "sample_count" field.
	SampleCount int `json:"sample_count,omitempty"`
	// Bottleneck holds the value of the "bottleneck" field.
	Bottleneck string `json:"bottleneck,omitempty"`
	// LastEvaluatedAt holds the value of the "last_evaluated_at" field.
	LastEvaluatedAt time.Time `json:"last_evaluated_at,omitempty"`
	// LastAlertedAt holds the value of the "last_alerted_at" field.
	LastAlertedAt *time.Time `json:"last_alerted_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PoolCapacityAlertState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case poolcapacityalertstate.FieldRemainingBalanceUsd, poolcapacityalertstate.FieldPoolAuthoritativeBalanceUsd, poolcapacityalertstate.FieldNormalEstimatedBalanceUsd, poolcapacityalertstate.FieldThresholdUsd, poolcapacityalertstate.FieldAvgAccountCost, poolcapacityalertstate.FieldAvgActualCost:
			values[i] = new(sql.NullFloat64)
		case poolcapacityalertstate.FieldID, poolcapacityalertstate.FieldGroupID, poolcapacityalertstate.FieldGroupGeneration, poolcapacityalertstate.FieldAccountID, poolcapacityalertstate.FieldAPIKeyID, poolcapacityalertstate.FieldUserID, poolcapacityalertstate.FieldBillingType, poolcapacityalertstate.FieldEpisode, poolcapacityalertstate.FieldPredictedRequests, poolcapacityalertstate.FieldPoolAccountCount, poolcapacityalertstate.FieldNormalAccountCount, poolcapacityalertstate.FieldSkippedAccountCount, poolcapacityalertstate.FieldUnknownAccountCount, poolcapacityalertstate.FieldStaleAccountCount, poolcapacityalertstate.FieldIncompatibleUnitAccountCount, poolcapacityalertstate.FieldThresholdRequests, poolcapacityalertstate.FieldAccountRequests, poolcapacityalertstate.FieldAPIKeyRequests, poolcapacityalertstate.FieldWalletRequests, poolcapacityalertstate.FieldSampleCount:
			values[i] = new(sql.NullInt64)
		case poolcapacityalertstate.FieldScopeType, poolcapacityalertstate.FieldStatus, poolcapacityalertstate.FieldAlertMetric, poolcapacityalertstate.FieldBottleneck:
			values[i] = new(sql.NullString)
		case poolcapacityalertstate.FieldLastEvaluatedAt, poolcapacityalertstate.FieldLastAlertedAt, poolcapacityalertstate.FieldCreatedAt, poolcapacityalertstate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PoolCapacityAlertState fields.
func (_m *PoolCapacityAlertState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case poolcapacityalertstate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case poolcapacityalertstate.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case poolcapacityalertstate.FieldGroupGeneration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_generation", values[i])
			} else if value.Valid {
				_m.GroupGeneration = value.Int64
			}
		case poolcapacityalertstate.FieldScopeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_type", values[i])
			} else if value.Valid {
				_m.ScopeType = value.String
			}
		case poolcapacityalertstate.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case poolcapacityalertstate.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int64)
				*_m.APIKeyID = value.Int64
			}
		case poolcapacityalertstate.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(int64)
				*_m.UserID = value.Int64
			}
		case poolcapacityalertstate.FieldBillingType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field billing_type", values[i])
			} else if value.Valid {
				_m.BillingType = new(int8)
				*_m.BillingType = int8(value.Int64)
			}
		case poolcapacityalertstate.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case poolcapacityalertstate.FieldEpisode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field episode", values[i])
			} else if value.Valid {
				_m.Episode = value.Int64
			}
		case poolcapacityalertstate.FieldAlertMetric:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alert_metric", values[i])
			} else if value.Valid {
				_m.AlertMetric = value.String
			}
		case poolcapacityalertstate.FieldPredictedRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field predicted_requests", values[i])
			} else if value.Valid {
				_m.PredictedRequests = new(int64)
				*_m.PredictedRequests = value.Int64
			}
		case poolcapacityalertstate.FieldRemainingBalanceUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field remaining_balance_usd", values[i])
			} else if value.Valid {
				_m.RemainingBalanceUsd = new(float64)
				*_m.RemainingBalanceUsd = value.Float64
			}
		case poolcapacityalertstate.FieldPoolAuthoritativeBalanceUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field pool_authoritative_balance_usd", values[i])
			} else if value.Valid {
				_m.PoolAuthoritativeBalanceUsd = new(float64)
				*_m.PoolAuthoritativeBalanceUsd = value.Float64
			}
		case poolcapacityalertstate.FieldNormalEstimatedBalanceUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field normal_estimated_balance_usd", values[i])
			} else if value.Valid {
				_m.NormalEstimatedBalanceUsd = new(float64)
				*_m.NormalEstimatedBalanceUsd = value.Float64
			}
		case poolcapacityalertstate.FieldPoolAccountCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pool_account_count", values[i])
			} else if value.Valid {
				_m.PoolAccountCount = int(value.Int64)
			}
		case poolcapacityalertstate.FieldNormalAccountCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field normal_account_count", values[i])
			} else if value.Valid {
				_m.NormalAccountCount = int(value.Int64)
			}
		case poolcapacityalertstate.FieldSkippedAccountCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field skipped_account_count", values[i])
			} else if value.Valid {
				_m.SkippedAccountCount = int(value.Int64)
			}
		case poolcapacityalertstate.FieldUnknownAccountCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field unknown_account_count", values[i])
			} else if value.Valid {
				_m.UnknownAccountCount = int(value.Int64)
			}
		case poolcapacityalertstate.FieldStaleAccountCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field stale_account_count", values[i])
			} else if value.Valid {
				_m.StaleAccountCount = int(value.Int64)
			}
		case poolcapacityalertstate.FieldIncompatibleUnitAccountCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field incompatible_unit_account_count", values[i])
			} else if value.Valid {
				_m.IncompatibleUnitAccountCount = int(value.Int64)
			}
		case poolcapacityalertstate.FieldThresholdRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field threshold_requests", values[i])
			} else if value.Valid {
				_m.ThresholdRequests = value.Int64
			}
		case poolcapacityalertstate.FieldThresholdUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field threshold_usd", values[i])
			} else if value.Valid {
				_m.ThresholdUsd = new(float64)
				*_m.ThresholdUsd = value.Float64
			}
		case poolcapacityalertstate.FieldAccountRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_requests", values[i])
			} else if value.Valid {
				_m.AccountRequests = new(int64)
				*_m.AccountRequests = value.Int64
			}
		case poolcapacityalertstate.FieldAPIKeyRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_requests", values[i])
			} else if value.Valid {
				_m.APIKeyRequests = new(int64)
				*_m.APIKeyRequests = value.Int64
			}
		case poolcapacityalertstate.FieldWalletRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_requests", values[i])
			} else if value.Valid {
				_m.WalletRequests = new(int64)
				*_m.WalletRequests = value.Int64
			}
		case poolcapacityalertstate.FieldAvgAccountCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field avg_account_cost", values[i])
			} else if value.Valid {
				_m.AvgAccountCost = value.Float64
			}
		case poolcapacityalertstate.FieldAvgActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field avg_actual_cost", values[i])
			} else if value.Valid {
				_m.AvgActualCost = value.Float64
			}
		case poolcapacityalertstate.FieldSampleCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sample_count", values[i])
			} else if value.Valid {
				_m.SampleCount = int(value.Int64)
			}
		case poolcapacityalertstate.FieldBottleneck:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bottleneck", values[i])
			} else if value.Valid {
				_m.Bottleneck = value.String
			}
		case poolcapacityalertstate.FieldLastEvaluatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_evaluated_at", values[i])
			} else if value.Valid {
				_m.LastEvaluatedAt = value.Time
			}
		case poolcapacityalertstate.FieldLastAlertedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_alerted_at", values[i])
			} else if value.Valid {
				_m.LastAlertedAt = new(time.Time)
				*_m.LastAlertedAt = value.Time
			}
		case poolcapacityalertstate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case poolcapacityalertstate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PoolCapacityAlertState.
// This includes values selected through modifiers, order, etc.
func (_m *PoolCapacityAlertState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PoolCapacityAlertState.
// Note that you need to call PoolCapacityAlertState.Unwrap() before calling this method if this PoolCapacityAlertState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PoolCapacityAlertState) Update() *PoolCapacityAlertStateUpdateOne {
	return NewPoolCapacityAlertStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PoolCapacityAlertState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PoolCapacityAlertState) Unwrap() *PoolCapacityAlertState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PoolCapacityAlertState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PoolCapacityAlertState) String() string {
	var builder strings.Builder
	builder.WriteString("PoolCapacityAlertState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("group_generation=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupGeneration))
	builder.WriteString(", ")
	builder.WriteString("scope_type=")
	builder.WriteString(_m.ScopeType)
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.BillingType; v != nil {
		builder.WriteString("billing_type=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("episode=")
	builder.WriteString(fmt.Sprintf("%v", _m.Episode))
	builder.WriteString(", ")
	builder.WriteString("alert_metric=")
	builder.WriteString(_m.AlertMetric)
	builder.WriteString(", ")
	if v := _m.PredictedRequests; v != nil {
		builder.WriteString("predicted_requests=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RemainingBalanceUsd; v != nil {
		builder.WriteString("remaining_balance_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PoolAuthoritativeBalanceUsd; v != nil {
		builder.WriteString("pool_authoritative_balance_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.NormalEstimatedBalanceUsd; v != nil {
		builder.WriteString("normal_estimated_balance_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("pool_account_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.PoolAccountCount))
	builder.WriteString(", ")
	builder.WriteString("normal_account_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.NormalAccountCount))
	builder.WriteString(", ")
	builder.WriteString("skipped_account_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkippedAccountCount))
	builder.WriteString(", ")
	builder.WriteString("unknown_account_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnknownAccountCount))
	builder.WriteString(", ")
	builder.WriteString("stale_account_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.StaleAccountCount))
	builder.WriteString(", ")
	builder.WriteString("incompatible_unit_account_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.IncompatibleUnitAccountCount))
	builder.WriteString(", ")
	builder.WriteString("threshold_requests=")
	builder.WriteString(fmt.Sprintf("%v", _m.ThresholdRequests))
	builder.WriteString(", ")
	if v := _m.ThresholdUsd; v != nil {
		builder.WriteString("threshold_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AccountRequests; v != nil {
		builder.WriteString("account_requests=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.APIKeyRequests; v != nil {
		builder.WriteString("api_key_requests=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.WalletRequests; v != nil {
		builder.WriteString("wallet_requests=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("avg_account_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvgAccountCost))
	builder.WriteString(", ")
	builder.WriteString("avg_actual_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvgActualCost))
	builder.WriteString(", ")
	builder.WriteString("sample_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SampleCount))
	builder.WriteString(", ")
	builder.WriteString("bottleneck=")
	builder.WriteString(_m.Bottleneck)
	builder.WriteString(", ")
	builder.WriteString("last_evaluated_at=")
	builder.WriteString(_m.LastEvaluatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastAlertedAt; v != nil {
		builder.WriteString("last_alerted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PoolCapacityAlertStates is a parsable slice of PoolCapacityAlertState.
type PoolCapacityAlertStates []*PoolCapacityAlertState
