// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/poolcapacityalertdelivery"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PoolCapacityAlertDeliveryDelete is the builder for deleting a PoolCapacityAlertDelivery entity.
type PoolCapacityAlertDeliveryDelete struct {
	config
	hooks    []Hook
	mutation *PoolCapacityAlertDeliveryMutation
}

// Where appends a list predicates to the PoolCapacityAlertDeliveryDelete builder.
func (_d *PoolCapacityAlertDeliveryDelete) Where(ps ...predicate.PoolCapacityAlertDelivery) *PoolCapacityAlertDeliveryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PoolCapacityAlertDeliveryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PoolCapacityAlertDeliveryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PoolCapacityAlertDeliveryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(poolcapacityalertdelivery.Table, sqlgraph.NewFieldSpec(poolcapacityalertdelivery.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PoolCapacityAlertDeliveryDeleteOne is the builder for deleting a single PoolCapacityAlertDelivery entity.
type PoolCapacityAlertDeliveryDeleteOne struct {
	_d *PoolCapacityAlertDeliveryDelete
}

// Where appends a list predicates to the PoolCapacityAlertDeliveryDelete builder.
func (_d *PoolCapacityAlertDeliveryDeleteOne) Where(ps ...predicate.PoolCapacityAlertDelivery) *PoolCapacityAlertDeliveryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PoolCapacityAlertDeliveryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{poolcapacityalertdelivery.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PoolCapacityAlertDeliveryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
