// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplangroup"
)

// SubscriptionPlanGroupCreate is the builder for creating a SubscriptionPlanGroup entity.
type SubscriptionPlanGroupCreate struct {
	config
	mutation *SubscriptionPlanGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPlanID sets the "plan_id" field.
func (_c *SubscriptionPlanGroupCreate) SetPlanID(v int64) *SubscriptionPlanGroupCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *SubscriptionPlanGroupCreate) SetGroupID(v int64) *SubscriptionPlanGroupCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *SubscriptionPlanGroupCreate) SetPriority(v int) *SubscriptionPlanGroupCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *SubscriptionPlanGroupCreate) SetNillablePriority(v *int) *SubscriptionPlanGroupCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionPlanGroupCreate) SetCreatedAt(v time.Time) *SubscriptionPlanGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionPlanGroupCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionPlanGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (_c *SubscriptionPlanGroupCreate) SetPlan(v *SubscriptionPlan) *SubscriptionPlanGroupCreate {
	return _c.SetPlanID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *SubscriptionPlanGroupCreate) SetGroup(v *Group) *SubscriptionPlanGroupCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the SubscriptionPlanGroupMutation object of the builder.
func (_c *SubscriptionPlanGroupCreate) Mutation() *SubscriptionPlanGroupMutation {
	return _c.mutation
}

// Save creates the SubscriptionPlanGroup in the database.
func (_c *SubscriptionPlanGroupCreate) Save(ctx context.Context) (*SubscriptionPlanGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionPlanGroupCreate) SaveX(ctx context.Context) *SubscriptionPlanGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPlanGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPlanGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionPlanGroupCreate) defaults() {
	if _, ok := _c.mutation.Priority(); !ok {
		v := subscriptionplangroup.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionplangroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionPlanGroupCreate) check() error {
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "SubscriptionPlanGroup.plan_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "SubscriptionPlanGroup.group_id"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "SubscriptionPlanGroup.priority"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionPlanGroup.created_at"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "SubscriptionPlanGroup.plan"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "SubscriptionPlanGroup.group"`)}
	}
	return nil
}

func (_c *SubscriptionPlanGroupCreate) sqlSave(ctx context.Context) (*SubscriptionPlanGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *SubscriptionPlanGroupCreate) createSpec() (*SubscriptionPlanGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionPlanGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionplangroup.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(subscriptionplangroup.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionplangroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscriptionplangroup.PlanTable,
			Columns: []string{subscriptionplangroup.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscriptionplangroup.GroupTable,
			Columns: []string{subscriptionplangroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionPlanGroup.Create().
//		SetPlanID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionPlanGroupUpsert) {
//			SetPlanID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionPlanGroupCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionPlanGroupUpsertOne {
	_c.conflict = opts
	return &SubscriptionPlanGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionPlanGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionPlanGroupCreate) OnConflictColumns(columns ...string) *SubscriptionPlanGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionPlanGroupUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionPlanGroupUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionPlanGroup node.
	SubscriptionPlanGroupUpsertOne struct {
		create *SubscriptionPlanGroupCreate
	}

	// SubscriptionPlanGroupUpsert is the "OnConflict" setter.
	SubscriptionPlanGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionPlanGroupUpsert) SetPlanID(v int64) *SubscriptionPlanGroupUpsert {
	u.Set(subscriptionplangroup.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionPlanGroupUpsert) UpdatePlanID() *SubscriptionPlanGroupUpsert {
	u.SetExcluded(subscriptionplangroup.FieldPlanID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionPlanGroupUpsert) SetGroupID(v int64) *SubscriptionPlanGroupUpsert {
	u.Set(subscriptionplangroup.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionPlanGroupUpsert) UpdateGroupID() *SubscriptionPlanGroupUpsert {
	u.SetExcluded(subscriptionplangroup.FieldGroupID)
	return u
}

// SetPriority sets the "priority" field.
func (u *SubscriptionPlanGroupUpsert) SetPriority(v int) *SubscriptionPlanGroupUpsert {
	u.Set(subscriptionplangroup.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SubscriptionPlanGroupUpsert) UpdatePriority() *SubscriptionPlanGroupUpsert {
	u.SetExcluded(subscriptionplangroup.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *SubscriptionPlanGroupUpsert) AddPriority(v int) *SubscriptionPlanGroupUpsert {
	u.Add(subscriptionplangroup.FieldPriority, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlanGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionPlanGroupUpsertOne) UpdateNewValues() *SubscriptionPlanGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionplangroup.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlanGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionPlanGroupUpsertOne) Ignore() *SubscriptionPlanGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionPlanGroupUpsertOne) DoNothing() *SubscriptionPlanGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionPlanGroupCreate.OnConflict
// documentation for more info.
func (u *SubscriptionPlanGroupUpsertOne) Update(set func(*SubscriptionPlanGroupUpsert)) *SubscriptionPlanGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionPlanGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionPlanGroupUpsertOne) SetPlanID(v int64) *SubscriptionPlanGroupUpsertOne {
	return u.Update(func(s *SubscriptionPlanGroupUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionPlanGroupUpsertOne) UpdatePlanID() *SubscriptionPlanGroupUpsertOne {
	return u.Update(func(s *SubscriptionPlanGroupUpsert) {
		s.UpdatePlanID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionPlanGroupUpsertOne) SetGroupID(v int64) *SubscriptionPlanGroupUpsertOne {
	return u.Update(func(s *SubscriptionPlanGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionPlanGroupUpsertOne) UpdateGroupID() *SubscriptionPlanGroupUpsertOne {
	return u.Update(func(s *SubscriptionPlanGroupUpsert) {
		s.UpdateGroupID()
	})
}

// SetPriority sets the "priority" field.
func (u *SubscriptionPlanGroupUpsertOne) SetPriority(v int) *SubscriptionPlanGroupUpsertOne {
	return u.Update(func(s *SubscriptionPlanGroupUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *SubscriptionPlanGroupUpsertOne) AddPriority(v int) *SubscriptionPlanGroupUpsertOne {
	return u.Update(func(s *SubscriptionPlanGroupUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SubscriptionPlanGroupUpsertOne) UpdatePriority() *SubscriptionPlanGroupUpsertOne {
	return u.Update(func(s *SubscriptionPlanGroupUpsert) {
		s.UpdatePriority()
	})
}

// Exec executes the query.
func (u *SubscriptionPlanGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionPlanGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionPlanGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// SubscriptionPlanGroupCreateBulk is the builder for creating many SubscriptionPlanGroup entities in bulk.
type SubscriptionPlanGroupCreateBulk struct {
	config
	err      error
	builders []*SubscriptionPlanGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionPlanGroup entities in the database.
func (_c *SubscriptionPlanGroupCreateBulk) Save(ctx context.Context) ([]*SubscriptionPlanGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionPlanGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionPlanGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionPlanGroupCreateBulk) SaveX(ctx context.Context) []*SubscriptionPlanGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPlanGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPlanGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionPlanGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionPlanGroupUpsert) {
//			SetPlanID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionPlanGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionPlanGroupUpsertBulk {
	_c.conflict = opts
	return &SubscriptionPlanGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionPlanGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionPlanGroupCreateBulk) OnConflictColumns(columns ...string) *SubscriptionPlanGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionPlanGroupUpsertBulk{
		create: _c,
	}
}

// SubscriptionPlanGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionPlanGroup nodes.
type SubscriptionPlanGroupUpsertBulk struct {
	create *SubscriptionPlanGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionPlanGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionPlanGroupUpsertBulk) UpdateNewValues() *SubscriptionPlanGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionplangroup.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlanGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionPlanGroupUpsertBulk) Ignore() *SubscriptionPlanGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionPlanGroupUpsertBulk) DoNothing() *SubscriptionPlanGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionPlanGroupCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionPlanGroupUpsertBulk) Update(set func(*SubscriptionPlanGroupUpsert)) *SubscriptionPlanGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionPlanGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionPlanGroupUpsertBulk) SetPlanID(v int64) *SubscriptionPlanGroupUpsertBulk {
	return u.Update(func(s *SubscriptionPlanGroupUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionPlanGroupUpsertBulk) UpdatePlanID() *SubscriptionPlanGroupUpsertBulk {
	return u.Update(func(s *SubscriptionPlanGroupUpsert) {
		s.UpdatePlanID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionPlanGroupUpsertBulk) SetGroupID(v int64) *SubscriptionPlanGroupUpsertBulk {
	return u.Update(func(s *SubscriptionPlanGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionPlanGroupUpsertBulk) UpdateGroupID() *SubscriptionPlanGroupUpsertBulk {
	return u.Update(func(s *SubscriptionPlanGroupUpsert) {
		s.UpdateGroupID()
	})
}

// SetPriority sets the "priority" field.
func (u *SubscriptionPlanGroupUpsertBulk) SetPriority(v int) *SubscriptionPlanGroupUpsertBulk {
	return u.Update(func(s *SubscriptionPlanGroupUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *SubscriptionPlanGroupUpsertBulk) AddPriority(v int) *SubscriptionPlanGroupUpsertBulk {
	return u.Update(func(s *SubscriptionPlanGroupUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SubscriptionPlanGroupUpsertBulk) UpdatePriority() *SubscriptionPlanGroupUpsertBulk {
	return u.Update(func(s *SubscriptionPlanGroupUpsert) {
		s.UpdatePriority()
	})
}

// Exec executes the query.
func (u *SubscriptionPlanGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionPlanGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionPlanGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionPlanGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
