export default {
  qqbot: {
    title: 'QQBot Management',
    description: 'Manage Tencent QQ bot runtime, credentials, messaging policies, account bindings, and diagnostics.',
    tabs: { overview: 'Overview', transport: 'Transport', config: 'Transport Configuration', messages: 'Messages & Welcome', bindings: 'Bindings', diagnostics: 'Diagnostics' },
    status: { enabled: 'Enabled', disabled: 'Disabled' },
    runtime: { disabled: 'Disabled', starting: 'Starting', running: 'Running', reloading: 'Reloading', degraded: 'Degraded', unknown: 'Unknown' },
    secrets: { configured: 'Configured', missing: 'Missing', keepPlaceholder: 'Leave blank to keep the current secret', keepHint: 'The server only returns configuration status. A blank value never clears or replaces the stored secret.' },
    overview: {
      title: 'Runtime Overview', description: 'Review bot activity, queue health, configuration versions, and binding trends.', transportMode: 'Current Transport', desiredState: 'Desired State', runtimeState: 'Runtime State', workers: 'Workers', completionRate: 'Completion Rate', configVersion: 'Config v{version}', activeVersion: 'Active v{version}', pendingJobs: '{count} pending', todayRequests: '{count} requests today', queueTitle: 'Event Queue', backlog: 'Backlog', pending: 'Pending', deadLetters: 'Dead Letters', queueCapacity: 'Capacity', activityTitle: 'Recent Activity', lastWebhook: 'Last Webhook', lastEvent: 'Last Event', lastSend: 'Last Send', lastError: 'Last Error', bindingTitle: 'Binding Statistics', totalRequests: '{count} total requests'
    },
    transport: {
      title: 'Transport', description: 'Choose the single message transport used by QQBot. Only the selected transport configuration is shown after switching.', selected: 'Selected', switching: 'Switching transport…', inherited: 'This selection was inherited from the pre-upgrade default. Confirm and save the transport you want to use.', modes: { botgo: 'Tencent Official BotGo', onebot: 'SnowLuma OneBot' }, botgoDescription: 'Receive guild and group events through Tencent’s official bot platform, configured with an AppID, AppSecret, and Webhook Secret.', onebotDescription: 'Receive OneBot v11 events through SnowLuma’s loopback reverse WebSocket, configured with a Self ID and Access Token.'
    },
    config: {
      title: 'Bot Configuration', description: 'Secrets are replaced only when a new value is submitted. The page never receives plaintext or ciphertext.', appId: 'AppID', appSecret: 'AppSecret', webhookSecret: 'Webhook Secret', sandbox: 'Sandbox', sandboxHint: 'Use Tencent bot sandbox endpoints and test scope.', publicBaseUrl: 'Public Base URL', publicBaseUrlHint: 'Used for webhook, domain validation, email binding, and /check image links. /check requires a Tencent-accessible HTTPS URL.', runtimeTitle: 'Runtime Parameters', workerCount: 'Worker Count', queueCapacity: 'Queue Capacity', apiTimeout: 'API Timeout (ms)', probeTitle: 'Tencent Connection Test', probeHint: 'A successful test is required before enabling a new configuration or rotated credentials.'
    },
    onebot: {
      title: 'SnowLuma / OneBot v11', description: 'Receive regular QQ group messages and join events through a loopback reverse WebSocket. It runs only when OneBot is the selected transport.', connected: 'Reverse WS connected', disconnected: 'Reverse WS disconnected', selfId: 'Bot QQ / Self ID', selfIdHint: 'Must match the account currently signed in to SnowLuma. Only a numeric ID is stored.', accessToken: 'Bearer Access Token', tokenHint: 'At least 32 characters. It is encrypted at rest and the API returns configuration status only.', reverseWsUrl: 'SnowLuma Reverse WebSocket URL', reverseWsHint: 'Use this loopback URL and the same token in SnowLuma. Keep ports 3010/3011 bound to loopback only.', actionTimeout: 'Action Timeout (ms)', enableRuntime: 'Enable OneBot event processing', runtimeState: 'Runtime State', workers: 'Workers', pendingActions: 'Pending Actions', lastConnection: 'Latest Connection Activity', requestApprovalTitle: 'Request Automation', requestApprovalHint: 'Disabled by default. Only OneBot request events delivered by SnowLuma are handled; bot group invitations are never accepted automatically.', autoApproveFriends: 'Auto-approve friend requests', autoApproveFriendsHint: 'When enabled, every incoming friend request for this bot QQ is approved.', autoApproveGroups: 'Auto-approve allowlisted group join requests', autoApproveGroupsHint: 'Approves user join requests only when the target group is listed in Allowed Group IDs; invitations are not processed.'
    },
    messages: {
      title: 'Messages & Welcome', description: 'Configure help replies, account binding, first-bind rewards, and group or guild welcome scope. Allowlisted groups can send /bind with an email directly; every group reply stays in its originating group.', bindingEnabled: 'Allow Account Binding', bindingEnabledHint: 'Pending links cannot be completed while disabled. Allowlisted groups can send /bind followed by an email directly.', welcomeEnabled: 'Member Welcome', welcomeEnabledHint: 'Send welcome messages for supported group or guild member events.', friendOpening: 'Friend-added Opening Message', friendOpeningHint: 'After a user actually adds the bot as a friend, OneBot sends one opening help message in that friend conversation. This rule cannot be disabled; ordinary direct messages, group temporary sessions, and group messages never trigger a private message.', channelCheckEnabled: 'Allow /check Channel Status Image', channelCheckEnabledHint: 'Enables /check status images. A public root HTTPS URL and an explicitly configured shared TOTP encryption key are also required.', firstBindBonus: 'First-bind Reward', linkTtl: 'Binding Link TTL (minutes)', commandCooldown: 'Command Cooldown (seconds)', commandCooldownHint: 'Isolated by user, command, and bot transport. /help, /bind, and /check show the precise remaining time while cooling down.', welcomeMessage: 'Member Welcome Message', welcomeMessageHint: "Supports the plain-text placeholders {'{'}site{'}'}, {'{'}user{'}'}, and {'{'}bind_command{'}'}. Command lines are omitted when binding or /check is disabled. Up to 4000 characters; currently {count}.", helpMessage: 'Help Message', helpMessageHint: 'Up to 4000 characters; currently {count}.', allowlistTitle: 'Group and Guild Scope', allowlistHint: 'An empty group or guild allowlist rejects that source type (fail-closed); it is not unrestricted. Values match Tencent IDs exactly.', allowedGroups: 'Allowed Group IDs', allowedGuilds: 'Allowed Guild IDs', onePerLine: 'One ID per line', welcomeChannels: 'Guild Welcome Channel Mapping', welcomeChannelsHint: 'Use “guild ID = channel ID”, one mapping per line.'
    },
    bindings: {
      title: 'Binding Records', description: '{count} records. Only masked emails and OpenID fingerprints are displayed.', filterStatus: 'Status', filterScene: 'Scene', filterSearch: 'Search masked email, QQ, or fingerprint', filterFrom: 'From', filterTo: 'To', empty: 'No binding records match the current filters.', status: 'Status', account: 'Account', scene: 'Scene', qq: 'Declared QQ', bonus: 'Reward', createdAt: 'Created', completedAt: 'Completed', completed: 'Completed', pending: 'Pending', expired: 'Expired', failed: 'Failed', revoked: 'Unbound', unbind: 'Unbind', pageInfo: 'Page {page} of {pages}', detailTitle: 'Binding Details', source: 'Source ID', channel: 'Channel ID', failureCode: 'Failure Code', delivery: 'Email / Notification', unbindTitle: 'Unbind QQBot Identity', unbindWarning: 'Unbinding removes the identity link only. Previously granted first-bind rewards are not reversed.', unbindReason: 'Reason', unbindReasonError: 'Enter a reason between 3 and 300 characters.', unbindConfirm: 'Confirm Unbind'
    },
    diagnostics: {
      title: 'Diagnostics', description: 'Verify Tencent entry points, configuration generations, connection tests, and the last stable error.', webhookUrl: 'Webhook URL', validationUrl: 'Domain Validation URL', configVersion: 'Saved Version', desiredVersion: 'Desired Version', activeVersion: 'Active Version', runtimeState: 'Runtime State', probeResult: 'Latest Connection Test', probeOk: 'Connection test passed', probeFailed: 'Connection test failed', noProbe: 'No connection test has been run in this page session.', lastError: 'Last Stable Error', errorCode: 'Error Code', errorTime: 'Occurred At', errorMessage: 'Message'
    },
    actions: { enabled: 'Enable QQBot', unsaved: 'Unsaved changes', synced: 'Synced with server', probe: 'Test Connection', probing: 'Testing…', unbinding: 'Unbinding…' },
    notices: { saved: 'QQBot configuration saved', transportUpdated: 'QQBot transport updated', probeSucceeded: 'Tencent connection test passed', oneBotSaved: 'OneBot configuration saved', oneBotProbeSucceeded: 'OneBot reverse WebSocket probe passed', unbound: 'Binding removed' },
    bindingStatus: { pending: 'Pending', completed: 'Completed', expired: 'Expired', revoked: 'Unbound', failed: 'Failed' },
    validation: { appId: 'Enter a numeric AppID with 1 to 64 digits.', oneBotSelfId: 'Enter a numeric Self ID with 5 to 20 digits.', oneBotToken: 'The OneBot token must contain at least 32 characters.', publicUrl: 'Enter a valid HTTP(S) public URL.', workers: 'Worker count must be an integer from 1 to 64.', queue: 'Queue capacity must be an integer from 100 to 100,000.', oneBotQueue: 'OneBot queue capacity must be an integer from 16 to 100,000.', timeout: 'API timeout must be between 500 and 30,000 milliseconds.', bonus: 'The first-bind reward cannot be negative.', ttl: 'Link TTL must be an integer from 5 to 1440 minutes.', welcome: 'The member welcome message cannot exceed 4000 characters.', help: 'The help message cannot exceed 4000 characters.', mapping: 'Invalid welcome channel mapping. Use “guild ID = channel ID”.' },
    errors: { loadConfig: 'Failed to load QQBot configuration.', updateTransport: 'Failed to update QQBot transport.', loadRuntime: 'Failed to load QQBot runtime.', loadOneBotConfig: 'Failed to load OneBot configuration.', loadOneBotRuntime: 'Failed to load OneBot runtime.', loadStats: 'Failed to load QQBot statistics.', loadBindings: 'Failed to load binding records.', saveConfig: 'Failed to save QQBot configuration.', saveOneBotConfig: 'Failed to save OneBot configuration.', probe: 'Connection test failed.', oneBotProbe: 'OneBot probe failed.', unbind: 'Failed to remove the binding.', credentialsRequired: 'AppID, AppSecret, and Webhook Secret must be configured before testing or enabling.', probeRequired: 'Run a successful connection test before enabling a new configuration or changed credentials.', oneBotCredentialsRequired: 'Enter a valid Self ID and configure a OneBot token containing at least 32 characters.', oneBotSaveBeforeProbe: 'Save the disabled OneBot configuration first, then wait for SnowLuma to establish the reverse WebSocket before probing.', oneBotProbeRequired: 'The current reverse WebSocket configuration must pass a probe before the OneBot runtime can be enabled.', QQBOT_PROBE_REQUIRED: 'These credentials have not passed the connection test yet.', QQBOT_CONFIG_CONFLICT: 'Another administrator updated this configuration. Refresh and try again.', QQBOT_TRANSPORT_NOT_SELECTED: 'Select the corresponding transport before using this action.' }
  }
}
