export default {
  qqbot: {
    title: 'QQBot Management',
    description: 'Manage Tencent QQ bot runtime, credentials, messaging policies, account bindings, and diagnostics.',
    tabs: { overview: 'Overview', config: 'Bot Configuration', messages: 'Messages & Welcome', bindings: 'Bindings', diagnostics: 'Diagnostics' },
    status: { enabled: 'Enabled', disabled: 'Disabled' },
    runtime: { disabled: 'Disabled', starting: 'Starting', running: 'Running', reloading: 'Reloading', degraded: 'Degraded', unknown: 'Unknown' },
    secrets: { configured: 'Configured', missing: 'Missing', keepPlaceholder: 'Leave blank to keep the current secret', keepHint: 'The server only returns configuration status. A blank value never clears or replaces the stored secret.' },
    overview: {
      title: 'Runtime Overview', description: 'Review bot activity, queue health, configuration versions, and binding trends.', desiredState: 'Desired State', runtimeState: 'Runtime State', workers: 'Workers', completionRate: 'Completion Rate', configVersion: 'Config v{version}', activeVersion: 'Active v{version}', pendingJobs: '{count} pending', todayRequests: '{count} requests today', queueTitle: 'Event Queue', backlog: 'Backlog', pending: 'Pending', deadLetters: 'Dead Letters', queueCapacity: 'Capacity', activityTitle: 'Recent Activity', lastWebhook: 'Last Webhook', lastEvent: 'Last Event', lastSend: 'Last Send', lastError: 'Last Error', bindingTitle: 'Binding Statistics', totalRequests: '{count} total requests'
    },
    config: {
      title: 'Bot Configuration', description: 'Secrets are replaced only when a new value is submitted. The page never receives plaintext or ciphertext.', appId: 'AppID', appSecret: 'AppSecret', webhookSecret: 'Webhook Secret', sandbox: 'Sandbox', sandboxHint: 'Use Tencent bot sandbox endpoints and test scope.', publicBaseUrl: 'Public Base URL', publicBaseUrlHint: 'Used for webhook, domain validation, email binding, and /check image links. /check requires a Tencent-accessible HTTPS URL.', runtimeTitle: 'Runtime Parameters', workerCount: 'Worker Count', queueCapacity: 'Queue Capacity', apiTimeout: 'API Timeout (ms)', probeTitle: 'Tencent Connection Test', probeHint: 'A successful test is required before enabling a new configuration or rotated credentials.'
    },
    messages: {
      title: 'Messages & Welcome', description: 'Configure help replies, account binding, first-bind rewards, and group or guild welcome scope.', bindingEnabled: 'Allow Account Binding', bindingEnabledHint: 'Pending links cannot be completed while disabled.', welcomeEnabled: 'Member Welcome', welcomeEnabledHint: 'Send welcome messages for supported guild member events.', firstInteraction: 'First Interaction Welcome', firstInteractionHint: 'Welcome a user on their first mention or direct message.', channelCheckEnabled: 'Allow /check Channel Status Image', channelCheckEnabledHint: 'Enables /check status images. A public root HTTPS URL and an explicitly configured shared TOTP encryption key are also required.', firstBindBonus: 'First-bind Reward', linkTtl: 'Binding Link TTL (minutes)', helpMessage: 'Help Message', helpMessageHint: 'Up to 4000 characters; currently {count}.', allowlistTitle: 'Group and Guild Scope', allowlistHint: 'An empty group or guild allowlist rejects that source type (fail-closed); it is not unrestricted. Values match Tencent IDs exactly.', allowedGroups: 'Allowed Group IDs', allowedGuilds: 'Allowed Guild IDs', onePerLine: 'One ID per line', welcomeChannels: 'Guild Welcome Channel Mapping', welcomeChannelsHint: 'Use “guild ID = channel ID”, one mapping per line.'
    },
    bindings: {
      title: 'Binding Records', description: '{count} records. Only masked emails and OpenID fingerprints are displayed.', filterStatus: 'Status', filterScene: 'Scene', filterSearch: 'Search masked email, QQ, or fingerprint', filterFrom: 'From', filterTo: 'To', empty: 'No binding records match the current filters.', status: 'Status', account: 'Account', scene: 'Scene', qq: 'Declared QQ', bonus: 'Reward', createdAt: 'Created', completedAt: 'Completed', completed: 'Completed', pending: 'Pending', expired: 'Expired', failed: 'Failed', revoked: 'Unbound', unbind: 'Unbind', pageInfo: 'Page {page} of {pages}', detailTitle: 'Binding Details', source: 'Source ID', channel: 'Channel ID', failureCode: 'Failure Code', delivery: 'Email / Notification', unbindTitle: 'Unbind QQBot Identity', unbindWarning: 'Unbinding removes the identity link only. Previously granted first-bind rewards are not reversed.', unbindReason: 'Reason', unbindReasonError: 'Enter a reason between 3 and 300 characters.', unbindConfirm: 'Confirm Unbind'
    },
    diagnostics: {
      title: 'Diagnostics', description: 'Verify Tencent entry points, configuration generations, connection tests, and the last stable error.', webhookUrl: 'Webhook URL', validationUrl: 'Domain Validation URL', configVersion: 'Saved Version', desiredVersion: 'Desired Version', activeVersion: 'Active Version', runtimeState: 'Runtime State', probeResult: 'Latest Connection Test', probeOk: 'Connection test passed', probeFailed: 'Connection test failed', noProbe: 'No connection test has been run in this page session.', lastError: 'Last Stable Error', errorCode: 'Error Code', errorTime: 'Occurred At', errorMessage: 'Message'
    },
    actions: { enabled: 'Enable QQBot', unsaved: 'Unsaved changes', synced: 'Synced with server', probe: 'Test Connection', probing: 'Testing…', unbinding: 'Unbinding…' },
    notices: { saved: 'QQBot configuration saved', probeSucceeded: 'Tencent connection test passed', unbound: 'Binding removed' },
    bindingStatus: { pending: 'Pending', completed: 'Completed', expired: 'Expired', revoked: 'Unbound', failed: 'Failed' },
    validation: { appId: 'Enter a numeric AppID with 1 to 64 digits.', publicUrl: 'Enter a valid HTTP(S) public URL.', workers: 'Worker count must be an integer from 1 to 64.', queue: 'Queue capacity must be an integer from 100 to 100,000.', timeout: 'API timeout must be between 500 and 30,000 milliseconds.', bonus: 'The first-bind reward cannot be negative.', ttl: 'Link TTL must be an integer from 5 to 1440 minutes.', help: 'The help message cannot exceed 4000 characters.', mapping: 'Invalid welcome channel mapping. Use “guild ID = channel ID”.' },
    errors: { loadConfig: 'Failed to load QQBot configuration.', loadRuntime: 'Failed to load QQBot runtime.', loadStats: 'Failed to load QQBot statistics.', loadBindings: 'Failed to load binding records.', saveConfig: 'Failed to save QQBot configuration.', probe: 'Connection test failed.', unbind: 'Failed to remove the binding.', credentialsRequired: 'AppID, AppSecret, and Webhook Secret must be configured before testing or enabling.', probeRequired: 'Run a successful connection test before enabling a new configuration or changed credentials.', QQBOT_PROBE_REQUIRED: 'These credentials have not passed the connection test yet.', QQBOT_CONFIG_CONFLICT: 'Another administrator updated this configuration. Refresh and try again.' }
  }
}
