// Code generated by ent, DO NOT EDIT.

package poolcapacityalertstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldID, id))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldGroupID, v))
}

// GroupGeneration applies equality check predicate on the "group_generation" field. It's identical to GroupGenerationEQ.
func GroupGeneration(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldGroupGeneration, v))
}

// ScopeType applies equality check predicate on the "scope_type" field. It's identical to ScopeTypeEQ.
func ScopeType(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldScopeType, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldAccountID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldAPIKeyID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldUserID, v))
}

// BillingType applies equality check predicate on the "billing_type" field. It's identical to BillingTypeEQ.
func BillingType(v int8) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldBillingType, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldStatus, v))
}

// Episode applies equality check predicate on the "episode" field. It's identical to EpisodeEQ.
func Episode(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldEpisode, v))
}

// AlertMetric applies equality check predicate on the "alert_metric" field. It's identical to AlertMetricEQ.
func AlertMetric(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldAlertMetric, v))
}

// PredictedRequests applies equality check predicate on the "predicted_requests" field. It's identical to PredictedRequestsEQ.
func PredictedRequests(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldPredictedRequests, v))
}

// RemainingBalanceUsd applies equality check predicate on the "remaining_balance_usd" field. It's identical to RemainingBalanceUsdEQ.
func RemainingBalanceUsd(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldRemainingBalanceUsd, v))
}

// PoolAuthoritativeBalanceUsd applies equality check predicate on the "pool_authoritative_balance_usd" field. It's identical to PoolAuthoritativeBalanceUsdEQ.
func PoolAuthoritativeBalanceUsd(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldPoolAuthoritativeBalanceUsd, v))
}

// NormalEstimatedBalanceUsd applies equality check predicate on the "normal_estimated_balance_usd" field. It's identical to NormalEstimatedBalanceUsdEQ.
func NormalEstimatedBalanceUsd(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldNormalEstimatedBalanceUsd, v))
}

// PoolAccountCount applies equality check predicate on the "pool_account_count" field. It's identical to PoolAccountCountEQ.
func PoolAccountCount(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldPoolAccountCount, v))
}

// NormalAccountCount applies equality check predicate on the "normal_account_count" field. It's identical to NormalAccountCountEQ.
func NormalAccountCount(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldNormalAccountCount, v))
}

// SkippedAccountCount applies equality check predicate on the "skipped_account_count" field. It's identical to SkippedAccountCountEQ.
func SkippedAccountCount(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldSkippedAccountCount, v))
}

// UnknownAccountCount applies equality check predicate on the "unknown_account_count" field. It's identical to UnknownAccountCountEQ.
func UnknownAccountCount(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldUnknownAccountCount, v))
}

// StaleAccountCount applies equality check predicate on the "stale_account_count" field. It's identical to StaleAccountCountEQ.
func StaleAccountCount(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldStaleAccountCount, v))
}

// IncompatibleUnitAccountCount applies equality check predicate on the "incompatible_unit_account_count" field. It's identical to IncompatibleUnitAccountCountEQ.
func IncompatibleUnitAccountCount(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldIncompatibleUnitAccountCount, v))
}

// ThresholdRequests applies equality check predicate on the "threshold_requests" field. It's identical to ThresholdRequestsEQ.
func ThresholdRequests(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldThresholdRequests, v))
}

// ThresholdUsd applies equality check predicate on the "threshold_usd" field. It's identical to ThresholdUsdEQ.
func ThresholdUsd(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldThresholdUsd, v))
}

// AccountRequests applies equality check predicate on the "account_requests" field. It's identical to AccountRequestsEQ.
func AccountRequests(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldAccountRequests, v))
}

// APIKeyRequests applies equality check predicate on the "api_key_requests" field. It's identical to APIKeyRequestsEQ.
func APIKeyRequests(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldAPIKeyRequests, v))
}

// WalletRequests applies equality check predicate on the "wallet_requests" field. It's identical to WalletRequestsEQ.
func WalletRequests(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldWalletRequests, v))
}

// AvgAccountCost applies equality check predicate on the "avg_account_cost" field. It's identical to AvgAccountCostEQ.
func AvgAccountCost(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldAvgAccountCost, v))
}

// AvgActualCost applies equality check predicate on the "avg_actual_cost" field. It's identical to AvgActualCostEQ.
func AvgActualCost(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldAvgActualCost, v))
}

// SampleCount applies equality check predicate on the "sample_count" field. It's identical to SampleCountEQ.
func SampleCount(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldSampleCount, v))
}

// Bottleneck applies equality check predicate on the "bottleneck" field. It's identical to BottleneckEQ.
func Bottleneck(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldBottleneck, v))
}

// LastEvaluatedAt applies equality check predicate on the "last_evaluated_at" field. It's identical to LastEvaluatedAtEQ.
func LastEvaluatedAt(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldLastEvaluatedAt, v))
}

// LastAlertedAt applies equality check predicate on the "last_alerted_at" field. It's identical to LastAlertedAtEQ.
func LastAlertedAt(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldLastAlertedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldGroupID, v))
}

// GroupGenerationEQ applies the EQ predicate on the "group_generation" field.
func GroupGenerationEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldGroupGeneration, v))
}

// GroupGenerationNEQ applies the NEQ predicate on the "group_generation" field.
func GroupGenerationNEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldGroupGeneration, v))
}

// GroupGenerationIn applies the In predicate on the "group_generation" field.
func GroupGenerationIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldGroupGeneration, vs...))
}

// GroupGenerationNotIn applies the NotIn predicate on the "group_generation" field.
func GroupGenerationNotIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldGroupGeneration, vs...))
}

// GroupGenerationGT applies the GT predicate on the "group_generation" field.
func GroupGenerationGT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldGroupGeneration, v))
}

// GroupGenerationGTE applies the GTE predicate on the "group_generation" field.
func GroupGenerationGTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldGroupGeneration, v))
}

// GroupGenerationLT applies the LT predicate on the "group_generation" field.
func GroupGenerationLT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldGroupGeneration, v))
}

// GroupGenerationLTE applies the LTE predicate on the "group_generation" field.
func GroupGenerationLTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldGroupGeneration, v))
}

// ScopeTypeEQ applies the EQ predicate on the "scope_type" field.
func ScopeTypeEQ(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldScopeType, v))
}

// ScopeTypeNEQ applies the NEQ predicate on the "scope_type" field.
func ScopeTypeNEQ(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldScopeType, v))
}

// ScopeTypeIn applies the In predicate on the "scope_type" field.
func ScopeTypeIn(vs ...string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldScopeType, vs...))
}

// ScopeTypeNotIn applies the NotIn predicate on the "scope_type" field.
func ScopeTypeNotIn(vs ...string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldScopeType, vs...))
}

// ScopeTypeGT applies the GT predicate on the "scope_type" field.
func ScopeTypeGT(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldScopeType, v))
}

// ScopeTypeGTE applies the GTE predicate on the "scope_type" field.
func ScopeTypeGTE(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldScopeType, v))
}

// ScopeTypeLT applies the LT predicate on the "scope_type" field.
func ScopeTypeLT(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldScopeType, v))
}

// ScopeTypeLTE applies the LTE predicate on the "scope_type" field.
func ScopeTypeLTE(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldScopeType, v))
}

// ScopeTypeContains applies the Contains predicate on the "scope_type" field.
func ScopeTypeContains(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldContains(FieldScopeType, v))
}

// ScopeTypeHasPrefix applies the HasPrefix predicate on the "scope_type" field.
func ScopeTypeHasPrefix(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldHasPrefix(FieldScopeType, v))
}

// ScopeTypeHasSuffix applies the HasSuffix predicate on the "scope_type" field.
func ScopeTypeHasSuffix(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldHasSuffix(FieldScopeType, v))
}

// ScopeTypeEqualFold applies the EqualFold predicate on the "scope_type" field.
func ScopeTypeEqualFold(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEqualFold(FieldScopeType, v))
}

// ScopeTypeContainsFold applies the ContainsFold predicate on the "scope_type" field.
func ScopeTypeContainsFold(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldContainsFold(FieldScopeType, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotNull(FieldAccountID))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotNull(FieldAPIKeyID))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotNull(FieldUserID))
}

// BillingTypeEQ applies the EQ predicate on the "billing_type" field.
func BillingTypeEQ(v int8) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldBillingType, v))
}

// BillingTypeNEQ applies the NEQ predicate on the "billing_type" field.
func BillingTypeNEQ(v int8) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldBillingType, v))
}

// BillingTypeIn applies the In predicate on the "billing_type" field.
func BillingTypeIn(vs ...int8) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldBillingType, vs...))
}

// BillingTypeNotIn applies the NotIn predicate on the "billing_type" field.
func BillingTypeNotIn(vs ...int8) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldBillingType, vs...))
}

// BillingTypeGT applies the GT predicate on the "billing_type" field.
func BillingTypeGT(v int8) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldBillingType, v))
}

// BillingTypeGTE applies the GTE predicate on the "billing_type" field.
func BillingTypeGTE(v int8) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldBillingType, v))
}

// BillingTypeLT applies the LT predicate on the "billing_type" field.
func BillingTypeLT(v int8) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldBillingType, v))
}

// BillingTypeLTE applies the LTE predicate on the "billing_type" field.
func BillingTypeLTE(v int8) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldBillingType, v))
}

// BillingTypeIsNil applies the IsNil predicate on the "billing_type" field.
func BillingTypeIsNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIsNull(FieldBillingType))
}

// BillingTypeNotNil applies the NotNil predicate on the "billing_type" field.
func BillingTypeNotNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotNull(FieldBillingType))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldContainsFold(FieldStatus, v))
}

// EpisodeEQ applies the EQ predicate on the "episode" field.
func EpisodeEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldEpisode, v))
}

// EpisodeNEQ applies the NEQ predicate on the "episode" field.
func EpisodeNEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldEpisode, v))
}

// EpisodeIn applies the In predicate on the "episode" field.
func EpisodeIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldEpisode, vs...))
}

// EpisodeNotIn applies the NotIn predicate on the "episode" field.
func EpisodeNotIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldEpisode, vs...))
}

// EpisodeGT applies the GT predicate on the "episode" field.
func EpisodeGT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldEpisode, v))
}

// EpisodeGTE applies the GTE predicate on the "episode" field.
func EpisodeGTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldEpisode, v))
}

// EpisodeLT applies the LT predicate on the "episode" field.
func EpisodeLT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldEpisode, v))
}

// EpisodeLTE applies the LTE predicate on the "episode" field.
func EpisodeLTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldEpisode, v))
}

// AlertMetricEQ applies the EQ predicate on the "alert_metric" field.
func AlertMetricEQ(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldAlertMetric, v))
}

// AlertMetricNEQ applies the NEQ predicate on the "alert_metric" field.
func AlertMetricNEQ(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldAlertMetric, v))
}

// AlertMetricIn applies the In predicate on the "alert_metric" field.
func AlertMetricIn(vs ...string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldAlertMetric, vs...))
}

// AlertMetricNotIn applies the NotIn predicate on the "alert_metric" field.
func AlertMetricNotIn(vs ...string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldAlertMetric, vs...))
}

// AlertMetricGT applies the GT predicate on the "alert_metric" field.
func AlertMetricGT(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldAlertMetric, v))
}

// AlertMetricGTE applies the GTE predicate on the "alert_metric" field.
func AlertMetricGTE(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldAlertMetric, v))
}

// AlertMetricLT applies the LT predicate on the "alert_metric" field.
func AlertMetricLT(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldAlertMetric, v))
}

// AlertMetricLTE applies the LTE predicate on the "alert_metric" field.
func AlertMetricLTE(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldAlertMetric, v))
}

// AlertMetricContains applies the Contains predicate on the "alert_metric" field.
func AlertMetricContains(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldContains(FieldAlertMetric, v))
}

// AlertMetricHasPrefix applies the HasPrefix predicate on the "alert_metric" field.
func AlertMetricHasPrefix(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldHasPrefix(FieldAlertMetric, v))
}

// AlertMetricHasSuffix applies the HasSuffix predicate on the "alert_metric" field.
func AlertMetricHasSuffix(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldHasSuffix(FieldAlertMetric, v))
}

// AlertMetricEqualFold applies the EqualFold predicate on the "alert_metric" field.
func AlertMetricEqualFold(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEqualFold(FieldAlertMetric, v))
}

// AlertMetricContainsFold applies the ContainsFold predicate on the "alert_metric" field.
func AlertMetricContainsFold(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldContainsFold(FieldAlertMetric, v))
}

// PredictedRequestsEQ applies the EQ predicate on the "predicted_requests" field.
func PredictedRequestsEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldPredictedRequests, v))
}

// PredictedRequestsNEQ applies the NEQ predicate on the "predicted_requests" field.
func PredictedRequestsNEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldPredictedRequests, v))
}

// PredictedRequestsIn applies the In predicate on the "predicted_requests" field.
func PredictedRequestsIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldPredictedRequests, vs...))
}

// PredictedRequestsNotIn applies the NotIn predicate on the "predicted_requests" field.
func PredictedRequestsNotIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldPredictedRequests, vs...))
}

// PredictedRequestsGT applies the GT predicate on the "predicted_requests" field.
func PredictedRequestsGT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldPredictedRequests, v))
}

// PredictedRequestsGTE applies the GTE predicate on the "predicted_requests" field.
func PredictedRequestsGTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldPredictedRequests, v))
}

// PredictedRequestsLT applies the LT predicate on the "predicted_requests" field.
func PredictedRequestsLT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldPredictedRequests, v))
}

// PredictedRequestsLTE applies the LTE predicate on the "predicted_requests" field.
func PredictedRequestsLTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldPredictedRequests, v))
}

// PredictedRequestsIsNil applies the IsNil predicate on the "predicted_requests" field.
func PredictedRequestsIsNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIsNull(FieldPredictedRequests))
}

// PredictedRequestsNotNil applies the NotNil predicate on the "predicted_requests" field.
func PredictedRequestsNotNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotNull(FieldPredictedRequests))
}

// RemainingBalanceUsdEQ applies the EQ predicate on the "remaining_balance_usd" field.
func RemainingBalanceUsdEQ(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldRemainingBalanceUsd, v))
}

// RemainingBalanceUsdNEQ applies the NEQ predicate on the "remaining_balance_usd" field.
func RemainingBalanceUsdNEQ(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldRemainingBalanceUsd, v))
}

// RemainingBalanceUsdIn applies the In predicate on the "remaining_balance_usd" field.
func RemainingBalanceUsdIn(vs ...float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldRemainingBalanceUsd, vs...))
}

// RemainingBalanceUsdNotIn applies the NotIn predicate on the "remaining_balance_usd" field.
func RemainingBalanceUsdNotIn(vs ...float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldRemainingBalanceUsd, vs...))
}

// RemainingBalanceUsdGT applies the GT predicate on the "remaining_balance_usd" field.
func RemainingBalanceUsdGT(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldRemainingBalanceUsd, v))
}

// RemainingBalanceUsdGTE applies the GTE predicate on the "remaining_balance_usd" field.
func RemainingBalanceUsdGTE(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldRemainingBalanceUsd, v))
}

// RemainingBalanceUsdLT applies the LT predicate on the "remaining_balance_usd" field.
func RemainingBalanceUsdLT(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldRemainingBalanceUsd, v))
}

// RemainingBalanceUsdLTE applies the LTE predicate on the "remaining_balance_usd" field.
func RemainingBalanceUsdLTE(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldRemainingBalanceUsd, v))
}

// RemainingBalanceUsdIsNil applies the IsNil predicate on the "remaining_balance_usd" field.
func RemainingBalanceUsdIsNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIsNull(FieldRemainingBalanceUsd))
}

// RemainingBalanceUsdNotNil applies the NotNil predicate on the "remaining_balance_usd" field.
func RemainingBalanceUsdNotNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotNull(FieldRemainingBalanceUsd))
}

// PoolAuthoritativeBalanceUsdEQ applies the EQ predicate on the "pool_authoritative_balance_usd" field.
func PoolAuthoritativeBalanceUsdEQ(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldPoolAuthoritativeBalanceUsd, v))
}

// PoolAuthoritativeBalanceUsdNEQ applies the NEQ predicate on the "pool_authoritative_balance_usd" field.
func PoolAuthoritativeBalanceUsdNEQ(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldPoolAuthoritativeBalanceUsd, v))
}

// PoolAuthoritativeBalanceUsdIn applies the In predicate on the "pool_authoritative_balance_usd" field.
func PoolAuthoritativeBalanceUsdIn(vs ...float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldPoolAuthoritativeBalanceUsd, vs...))
}

// PoolAuthoritativeBalanceUsdNotIn applies the NotIn predicate on the "pool_authoritative_balance_usd" field.
func PoolAuthoritativeBalanceUsdNotIn(vs ...float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldPoolAuthoritativeBalanceUsd, vs...))
}

// PoolAuthoritativeBalanceUsdGT applies the GT predicate on the "pool_authoritative_balance_usd" field.
func PoolAuthoritativeBalanceUsdGT(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldPoolAuthoritativeBalanceUsd, v))
}

// PoolAuthoritativeBalanceUsdGTE applies the GTE predicate on the "pool_authoritative_balance_usd" field.
func PoolAuthoritativeBalanceUsdGTE(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldPoolAuthoritativeBalanceUsd, v))
}

// PoolAuthoritativeBalanceUsdLT applies the LT predicate on the "pool_authoritative_balance_usd" field.
func PoolAuthoritativeBalanceUsdLT(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldPoolAuthoritativeBalanceUsd, v))
}

// PoolAuthoritativeBalanceUsdLTE applies the LTE predicate on the "pool_authoritative_balance_usd" field.
func PoolAuthoritativeBalanceUsdLTE(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldPoolAuthoritativeBalanceUsd, v))
}

// PoolAuthoritativeBalanceUsdIsNil applies the IsNil predicate on the "pool_authoritative_balance_usd" field.
func PoolAuthoritativeBalanceUsdIsNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIsNull(FieldPoolAuthoritativeBalanceUsd))
}

// PoolAuthoritativeBalanceUsdNotNil applies the NotNil predicate on the "pool_authoritative_balance_usd" field.
func PoolAuthoritativeBalanceUsdNotNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotNull(FieldPoolAuthoritativeBalanceUsd))
}

// NormalEstimatedBalanceUsdEQ applies the EQ predicate on the "normal_estimated_balance_usd" field.
func NormalEstimatedBalanceUsdEQ(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldNormalEstimatedBalanceUsd, v))
}

// NormalEstimatedBalanceUsdNEQ applies the NEQ predicate on the "normal_estimated_balance_usd" field.
func NormalEstimatedBalanceUsdNEQ(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldNormalEstimatedBalanceUsd, v))
}

// NormalEstimatedBalanceUsdIn applies the In predicate on the "normal_estimated_balance_usd" field.
func NormalEstimatedBalanceUsdIn(vs ...float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldNormalEstimatedBalanceUsd, vs...))
}

// NormalEstimatedBalanceUsdNotIn applies the NotIn predicate on the "normal_estimated_balance_usd" field.
func NormalEstimatedBalanceUsdNotIn(vs ...float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldNormalEstimatedBalanceUsd, vs...))
}

// NormalEstimatedBalanceUsdGT applies the GT predicate on the "normal_estimated_balance_usd" field.
func NormalEstimatedBalanceUsdGT(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldNormalEstimatedBalanceUsd, v))
}

// NormalEstimatedBalanceUsdGTE applies the GTE predicate on the "normal_estimated_balance_usd" field.
func NormalEstimatedBalanceUsdGTE(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldNormalEstimatedBalanceUsd, v))
}

// NormalEstimatedBalanceUsdLT applies the LT predicate on the "normal_estimated_balance_usd" field.
func NormalEstimatedBalanceUsdLT(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldNormalEstimatedBalanceUsd, v))
}

// NormalEstimatedBalanceUsdLTE applies the LTE predicate on the "normal_estimated_balance_usd" field.
func NormalEstimatedBalanceUsdLTE(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldNormalEstimatedBalanceUsd, v))
}

// NormalEstimatedBalanceUsdIsNil applies the IsNil predicate on the "normal_estimated_balance_usd" field.
func NormalEstimatedBalanceUsdIsNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIsNull(FieldNormalEstimatedBalanceUsd))
}

// NormalEstimatedBalanceUsdNotNil applies the NotNil predicate on the "normal_estimated_balance_usd" field.
func NormalEstimatedBalanceUsdNotNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotNull(FieldNormalEstimatedBalanceUsd))
}

// PoolAccountCountEQ applies the EQ predicate on the "pool_account_count" field.
func PoolAccountCountEQ(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldPoolAccountCount, v))
}

// PoolAccountCountNEQ applies the NEQ predicate on the "pool_account_count" field.
func PoolAccountCountNEQ(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldPoolAccountCount, v))
}

// PoolAccountCountIn applies the In predicate on the "pool_account_count" field.
func PoolAccountCountIn(vs ...int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldPoolAccountCount, vs...))
}

// PoolAccountCountNotIn applies the NotIn predicate on the "pool_account_count" field.
func PoolAccountCountNotIn(vs ...int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldPoolAccountCount, vs...))
}

// PoolAccountCountGT applies the GT predicate on the "pool_account_count" field.
func PoolAccountCountGT(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldPoolAccountCount, v))
}

// PoolAccountCountGTE applies the GTE predicate on the "pool_account_count" field.
func PoolAccountCountGTE(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldPoolAccountCount, v))
}

// PoolAccountCountLT applies the LT predicate on the "pool_account_count" field.
func PoolAccountCountLT(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldPoolAccountCount, v))
}

// PoolAccountCountLTE applies the LTE predicate on the "pool_account_count" field.
func PoolAccountCountLTE(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldPoolAccountCount, v))
}

// NormalAccountCountEQ applies the EQ predicate on the "normal_account_count" field.
func NormalAccountCountEQ(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldNormalAccountCount, v))
}

// NormalAccountCountNEQ applies the NEQ predicate on the "normal_account_count" field.
func NormalAccountCountNEQ(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldNormalAccountCount, v))
}

// NormalAccountCountIn applies the In predicate on the "normal_account_count" field.
func NormalAccountCountIn(vs ...int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldNormalAccountCount, vs...))
}

// NormalAccountCountNotIn applies the NotIn predicate on the "normal_account_count" field.
func NormalAccountCountNotIn(vs ...int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldNormalAccountCount, vs...))
}

// NormalAccountCountGT applies the GT predicate on the "normal_account_count" field.
func NormalAccountCountGT(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldNormalAccountCount, v))
}

// NormalAccountCountGTE applies the GTE predicate on the "normal_account_count" field.
func NormalAccountCountGTE(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldNormalAccountCount, v))
}

// NormalAccountCountLT applies the LT predicate on the "normal_account_count" field.
func NormalAccountCountLT(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldNormalAccountCount, v))
}

// NormalAccountCountLTE applies the LTE predicate on the "normal_account_count" field.
func NormalAccountCountLTE(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldNormalAccountCount, v))
}

// SkippedAccountCountEQ applies the EQ predicate on the "skipped_account_count" field.
func SkippedAccountCountEQ(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldSkippedAccountCount, v))
}

// SkippedAccountCountNEQ applies the NEQ predicate on the "skipped_account_count" field.
func SkippedAccountCountNEQ(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldSkippedAccountCount, v))
}

// SkippedAccountCountIn applies the In predicate on the "skipped_account_count" field.
func SkippedAccountCountIn(vs ...int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldSkippedAccountCount, vs...))
}

// SkippedAccountCountNotIn applies the NotIn predicate on the "skipped_account_count" field.
func SkippedAccountCountNotIn(vs ...int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldSkippedAccountCount, vs...))
}

// SkippedAccountCountGT applies the GT predicate on the "skipped_account_count" field.
func SkippedAccountCountGT(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldSkippedAccountCount, v))
}

// SkippedAccountCountGTE applies the GTE predicate on the "skipped_account_count" field.
func SkippedAccountCountGTE(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldSkippedAccountCount, v))
}

// SkippedAccountCountLT applies the LT predicate on the "skipped_account_count" field.
func SkippedAccountCountLT(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldSkippedAccountCount, v))
}

// SkippedAccountCountLTE applies the LTE predicate on the "skipped_account_count" field.
func SkippedAccountCountLTE(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldSkippedAccountCount, v))
}

// UnknownAccountCountEQ applies the EQ predicate on the "unknown_account_count" field.
func UnknownAccountCountEQ(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldUnknownAccountCount, v))
}

// UnknownAccountCountNEQ applies the NEQ predicate on the "unknown_account_count" field.
func UnknownAccountCountNEQ(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldUnknownAccountCount, v))
}

// UnknownAccountCountIn applies the In predicate on the "unknown_account_count" field.
func UnknownAccountCountIn(vs ...int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldUnknownAccountCount, vs...))
}

// UnknownAccountCountNotIn applies the NotIn predicate on the "unknown_account_count" field.
func UnknownAccountCountNotIn(vs ...int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldUnknownAccountCount, vs...))
}

// UnknownAccountCountGT applies the GT predicate on the "unknown_account_count" field.
func UnknownAccountCountGT(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldUnknownAccountCount, v))
}

// UnknownAccountCountGTE applies the GTE predicate on the "unknown_account_count" field.
func UnknownAccountCountGTE(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldUnknownAccountCount, v))
}

// UnknownAccountCountLT applies the LT predicate on the "unknown_account_count" field.
func UnknownAccountCountLT(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldUnknownAccountCount, v))
}

// UnknownAccountCountLTE applies the LTE predicate on the "unknown_account_count" field.
func UnknownAccountCountLTE(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldUnknownAccountCount, v))
}

// StaleAccountCountEQ applies the EQ predicate on the "stale_account_count" field.
func StaleAccountCountEQ(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldStaleAccountCount, v))
}

// StaleAccountCountNEQ applies the NEQ predicate on the "stale_account_count" field.
func StaleAccountCountNEQ(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldStaleAccountCount, v))
}

// StaleAccountCountIn applies the In predicate on the "stale_account_count" field.
func StaleAccountCountIn(vs ...int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldStaleAccountCount, vs...))
}

// StaleAccountCountNotIn applies the NotIn predicate on the "stale_account_count" field.
func StaleAccountCountNotIn(vs ...int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldStaleAccountCount, vs...))
}

// StaleAccountCountGT applies the GT predicate on the "stale_account_count" field.
func StaleAccountCountGT(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldStaleAccountCount, v))
}

// StaleAccountCountGTE applies the GTE predicate on the "stale_account_count" field.
func StaleAccountCountGTE(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldStaleAccountCount, v))
}

// StaleAccountCountLT applies the LT predicate on the "stale_account_count" field.
func StaleAccountCountLT(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldStaleAccountCount, v))
}

// StaleAccountCountLTE applies the LTE predicate on the "stale_account_count" field.
func StaleAccountCountLTE(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldStaleAccountCount, v))
}

// IncompatibleUnitAccountCountEQ applies the EQ predicate on the "incompatible_unit_account_count" field.
func IncompatibleUnitAccountCountEQ(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldIncompatibleUnitAccountCount, v))
}

// IncompatibleUnitAccountCountNEQ applies the NEQ predicate on the "incompatible_unit_account_count" field.
func IncompatibleUnitAccountCountNEQ(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldIncompatibleUnitAccountCount, v))
}

// IncompatibleUnitAccountCountIn applies the In predicate on the "incompatible_unit_account_count" field.
func IncompatibleUnitAccountCountIn(vs ...int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldIncompatibleUnitAccountCount, vs...))
}

// IncompatibleUnitAccountCountNotIn applies the NotIn predicate on the "incompatible_unit_account_count" field.
func IncompatibleUnitAccountCountNotIn(vs ...int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldIncompatibleUnitAccountCount, vs...))
}

// IncompatibleUnitAccountCountGT applies the GT predicate on the "incompatible_unit_account_count" field.
func IncompatibleUnitAccountCountGT(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldIncompatibleUnitAccountCount, v))
}

// IncompatibleUnitAccountCountGTE applies the GTE predicate on the "incompatible_unit_account_count" field.
func IncompatibleUnitAccountCountGTE(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldIncompatibleUnitAccountCount, v))
}

// IncompatibleUnitAccountCountLT applies the LT predicate on the "incompatible_unit_account_count" field.
func IncompatibleUnitAccountCountLT(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldIncompatibleUnitAccountCount, v))
}

// IncompatibleUnitAccountCountLTE applies the LTE predicate on the "incompatible_unit_account_count" field.
func IncompatibleUnitAccountCountLTE(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldIncompatibleUnitAccountCount, v))
}

// ThresholdRequestsEQ applies the EQ predicate on the "threshold_requests" field.
func ThresholdRequestsEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldThresholdRequests, v))
}

// ThresholdRequestsNEQ applies the NEQ predicate on the "threshold_requests" field.
func ThresholdRequestsNEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldThresholdRequests, v))
}

// ThresholdRequestsIn applies the In predicate on the "threshold_requests" field.
func ThresholdRequestsIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldThresholdRequests, vs...))
}

// ThresholdRequestsNotIn applies the NotIn predicate on the "threshold_requests" field.
func ThresholdRequestsNotIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldThresholdRequests, vs...))
}

// ThresholdRequestsGT applies the GT predicate on the "threshold_requests" field.
func ThresholdRequestsGT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldThresholdRequests, v))
}

// ThresholdRequestsGTE applies the GTE predicate on the "threshold_requests" field.
func ThresholdRequestsGTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldThresholdRequests, v))
}

// ThresholdRequestsLT applies the LT predicate on the "threshold_requests" field.
func ThresholdRequestsLT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldThresholdRequests, v))
}

// ThresholdRequestsLTE applies the LTE predicate on the "threshold_requests" field.
func ThresholdRequestsLTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldThresholdRequests, v))
}

// ThresholdUsdEQ applies the EQ predicate on the "threshold_usd" field.
func ThresholdUsdEQ(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldThresholdUsd, v))
}

// ThresholdUsdNEQ applies the NEQ predicate on the "threshold_usd" field.
func ThresholdUsdNEQ(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldThresholdUsd, v))
}

// ThresholdUsdIn applies the In predicate on the "threshold_usd" field.
func ThresholdUsdIn(vs ...float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldThresholdUsd, vs...))
}

// ThresholdUsdNotIn applies the NotIn predicate on the "threshold_usd" field.
func ThresholdUsdNotIn(vs ...float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldThresholdUsd, vs...))
}

// ThresholdUsdGT applies the GT predicate on the "threshold_usd" field.
func ThresholdUsdGT(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldThresholdUsd, v))
}

// ThresholdUsdGTE applies the GTE predicate on the "threshold_usd" field.
func ThresholdUsdGTE(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldThresholdUsd, v))
}

// ThresholdUsdLT applies the LT predicate on the "threshold_usd" field.
func ThresholdUsdLT(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldThresholdUsd, v))
}

// ThresholdUsdLTE applies the LTE predicate on the "threshold_usd" field.
func ThresholdUsdLTE(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldThresholdUsd, v))
}

// ThresholdUsdIsNil applies the IsNil predicate on the "threshold_usd" field.
func ThresholdUsdIsNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIsNull(FieldThresholdUsd))
}

// ThresholdUsdNotNil applies the NotNil predicate on the "threshold_usd" field.
func ThresholdUsdNotNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotNull(FieldThresholdUsd))
}

// AccountRequestsEQ applies the EQ predicate on the "account_requests" field.
func AccountRequestsEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldAccountRequests, v))
}

// AccountRequestsNEQ applies the NEQ predicate on the "account_requests" field.
func AccountRequestsNEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldAccountRequests, v))
}

// AccountRequestsIn applies the In predicate on the "account_requests" field.
func AccountRequestsIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldAccountRequests, vs...))
}

// AccountRequestsNotIn applies the NotIn predicate on the "account_requests" field.
func AccountRequestsNotIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldAccountRequests, vs...))
}

// AccountRequestsGT applies the GT predicate on the "account_requests" field.
func AccountRequestsGT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldAccountRequests, v))
}

// AccountRequestsGTE applies the GTE predicate on the "account_requests" field.
func AccountRequestsGTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldAccountRequests, v))
}

// AccountRequestsLT applies the LT predicate on the "account_requests" field.
func AccountRequestsLT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldAccountRequests, v))
}

// AccountRequestsLTE applies the LTE predicate on the "account_requests" field.
func AccountRequestsLTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldAccountRequests, v))
}

// AccountRequestsIsNil applies the IsNil predicate on the "account_requests" field.
func AccountRequestsIsNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIsNull(FieldAccountRequests))
}

// AccountRequestsNotNil applies the NotNil predicate on the "account_requests" field.
func AccountRequestsNotNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotNull(FieldAccountRequests))
}

// APIKeyRequestsEQ applies the EQ predicate on the "api_key_requests" field.
func APIKeyRequestsEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldAPIKeyRequests, v))
}

// APIKeyRequestsNEQ applies the NEQ predicate on the "api_key_requests" field.
func APIKeyRequestsNEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldAPIKeyRequests, v))
}

// APIKeyRequestsIn applies the In predicate on the "api_key_requests" field.
func APIKeyRequestsIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldAPIKeyRequests, vs...))
}

// APIKeyRequestsNotIn applies the NotIn predicate on the "api_key_requests" field.
func APIKeyRequestsNotIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldAPIKeyRequests, vs...))
}

// APIKeyRequestsGT applies the GT predicate on the "api_key_requests" field.
func APIKeyRequestsGT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldAPIKeyRequests, v))
}

// APIKeyRequestsGTE applies the GTE predicate on the "api_key_requests" field.
func APIKeyRequestsGTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldAPIKeyRequests, v))
}

// APIKeyRequestsLT applies the LT predicate on the "api_key_requests" field.
func APIKeyRequestsLT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldAPIKeyRequests, v))
}

// APIKeyRequestsLTE applies the LTE predicate on the "api_key_requests" field.
func APIKeyRequestsLTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldAPIKeyRequests, v))
}

// APIKeyRequestsIsNil applies the IsNil predicate on the "api_key_requests" field.
func APIKeyRequestsIsNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIsNull(FieldAPIKeyRequests))
}

// APIKeyRequestsNotNil applies the NotNil predicate on the "api_key_requests" field.
func APIKeyRequestsNotNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotNull(FieldAPIKeyRequests))
}

// WalletRequestsEQ applies the EQ predicate on the "wallet_requests" field.
func WalletRequestsEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldWalletRequests, v))
}

// WalletRequestsNEQ applies the NEQ predicate on the "wallet_requests" field.
func WalletRequestsNEQ(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldWalletRequests, v))
}

// WalletRequestsIn applies the In predicate on the "wallet_requests" field.
func WalletRequestsIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldWalletRequests, vs...))
}

// WalletRequestsNotIn applies the NotIn predicate on the "wallet_requests" field.
func WalletRequestsNotIn(vs ...int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldWalletRequests, vs...))
}

// WalletRequestsGT applies the GT predicate on the "wallet_requests" field.
func WalletRequestsGT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldWalletRequests, v))
}

// WalletRequestsGTE applies the GTE predicate on the "wallet_requests" field.
func WalletRequestsGTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldWalletRequests, v))
}

// WalletRequestsLT applies the LT predicate on the "wallet_requests" field.
func WalletRequestsLT(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldWalletRequests, v))
}

// WalletRequestsLTE applies the LTE predicate on the "wallet_requests" field.
func WalletRequestsLTE(v int64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldWalletRequests, v))
}

// WalletRequestsIsNil applies the IsNil predicate on the "wallet_requests" field.
func WalletRequestsIsNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIsNull(FieldWalletRequests))
}

// WalletRequestsNotNil applies the NotNil predicate on the "wallet_requests" field.
func WalletRequestsNotNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotNull(FieldWalletRequests))
}

// AvgAccountCostEQ applies the EQ predicate on the "avg_account_cost" field.
func AvgAccountCostEQ(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldAvgAccountCost, v))
}

// AvgAccountCostNEQ applies the NEQ predicate on the "avg_account_cost" field.
func AvgAccountCostNEQ(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldAvgAccountCost, v))
}

// AvgAccountCostIn applies the In predicate on the "avg_account_cost" field.
func AvgAccountCostIn(vs ...float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldAvgAccountCost, vs...))
}

// AvgAccountCostNotIn applies the NotIn predicate on the "avg_account_cost" field.
func AvgAccountCostNotIn(vs ...float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldAvgAccountCost, vs...))
}

// AvgAccountCostGT applies the GT predicate on the "avg_account_cost" field.
func AvgAccountCostGT(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldAvgAccountCost, v))
}

// AvgAccountCostGTE applies the GTE predicate on the "avg_account_cost" field.
func AvgAccountCostGTE(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldAvgAccountCost, v))
}

// AvgAccountCostLT applies the LT predicate on the "avg_account_cost" field.
func AvgAccountCostLT(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldAvgAccountCost, v))
}

// AvgAccountCostLTE applies the LTE predicate on the "avg_account_cost" field.
func AvgAccountCostLTE(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldAvgAccountCost, v))
}

// AvgActualCostEQ applies the EQ predicate on the "avg_actual_cost" field.
func AvgActualCostEQ(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldAvgActualCost, v))
}

// AvgActualCostNEQ applies the NEQ predicate on the "avg_actual_cost" field.
func AvgActualCostNEQ(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldAvgActualCost, v))
}

// AvgActualCostIn applies the In predicate on the "avg_actual_cost" field.
func AvgActualCostIn(vs ...float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldAvgActualCost, vs...))
}

// AvgActualCostNotIn applies the NotIn predicate on the "avg_actual_cost" field.
func AvgActualCostNotIn(vs ...float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldAvgActualCost, vs...))
}

// AvgActualCostGT applies the GT predicate on the "avg_actual_cost" field.
func AvgActualCostGT(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldAvgActualCost, v))
}

// AvgActualCostGTE applies the GTE predicate on the "avg_actual_cost" field.
func AvgActualCostGTE(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldAvgActualCost, v))
}

// AvgActualCostLT applies the LT predicate on the "avg_actual_cost" field.
func AvgActualCostLT(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldAvgActualCost, v))
}

// AvgActualCostLTE applies the LTE predicate on the "avg_actual_cost" field.
func AvgActualCostLTE(v float64) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldAvgActualCost, v))
}

// SampleCountEQ applies the EQ predicate on the "sample_count" field.
func SampleCountEQ(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldSampleCount, v))
}

// SampleCountNEQ applies the NEQ predicate on the "sample_count" field.
func SampleCountNEQ(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldSampleCount, v))
}

// SampleCountIn applies the In predicate on the "sample_count" field.
func SampleCountIn(vs ...int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldSampleCount, vs...))
}

// SampleCountNotIn applies the NotIn predicate on the "sample_count" field.
func SampleCountNotIn(vs ...int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldSampleCount, vs...))
}

// SampleCountGT applies the GT predicate on the "sample_count" field.
func SampleCountGT(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldSampleCount, v))
}

// SampleCountGTE applies the GTE predicate on the "sample_count" field.
func SampleCountGTE(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldSampleCount, v))
}

// SampleCountLT applies the LT predicate on the "sample_count" field.
func SampleCountLT(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldSampleCount, v))
}

// SampleCountLTE applies the LTE predicate on the "sample_count" field.
func SampleCountLTE(v int) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldSampleCount, v))
}

// BottleneckEQ applies the EQ predicate on the "bottleneck" field.
func BottleneckEQ(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldBottleneck, v))
}

// BottleneckNEQ applies the NEQ predicate on the "bottleneck" field.
func BottleneckNEQ(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldBottleneck, v))
}

// BottleneckIn applies the In predicate on the "bottleneck" field.
func BottleneckIn(vs ...string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldBottleneck, vs...))
}

// BottleneckNotIn applies the NotIn predicate on the "bottleneck" field.
func BottleneckNotIn(vs ...string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldBottleneck, vs...))
}

// BottleneckGT applies the GT predicate on the "bottleneck" field.
func BottleneckGT(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldBottleneck, v))
}

// BottleneckGTE applies the GTE predicate on the "bottleneck" field.
func BottleneckGTE(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldBottleneck, v))
}

// BottleneckLT applies the LT predicate on the "bottleneck" field.
func BottleneckLT(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldBottleneck, v))
}

// BottleneckLTE applies the LTE predicate on the "bottleneck" field.
func BottleneckLTE(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldBottleneck, v))
}

// BottleneckContains applies the Contains predicate on the "bottleneck" field.
func BottleneckContains(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldContains(FieldBottleneck, v))
}

// BottleneckHasPrefix applies the HasPrefix predicate on the "bottleneck" field.
func BottleneckHasPrefix(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldHasPrefix(FieldBottleneck, v))
}

// BottleneckHasSuffix applies the HasSuffix predicate on the "bottleneck" field.
func BottleneckHasSuffix(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldHasSuffix(FieldBottleneck, v))
}

// BottleneckEqualFold applies the EqualFold predicate on the "bottleneck" field.
func BottleneckEqualFold(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEqualFold(FieldBottleneck, v))
}

// BottleneckContainsFold applies the ContainsFold predicate on the "bottleneck" field.
func BottleneckContainsFold(v string) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldContainsFold(FieldBottleneck, v))
}

// LastEvaluatedAtEQ applies the EQ predicate on the "last_evaluated_at" field.
func LastEvaluatedAtEQ(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtNEQ applies the NEQ predicate on the "last_evaluated_at" field.
func LastEvaluatedAtNEQ(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtIn applies the In predicate on the "last_evaluated_at" field.
func LastEvaluatedAtIn(vs ...time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldLastEvaluatedAt, vs...))
}

// LastEvaluatedAtNotIn applies the NotIn predicate on the "last_evaluated_at" field.
func LastEvaluatedAtNotIn(vs ...time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldLastEvaluatedAt, vs...))
}

// LastEvaluatedAtGT applies the GT predicate on the "last_evaluated_at" field.
func LastEvaluatedAtGT(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtGTE applies the GTE predicate on the "last_evaluated_at" field.
func LastEvaluatedAtGTE(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtLT applies the LT predicate on the "last_evaluated_at" field.
func LastEvaluatedAtLT(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtLTE applies the LTE predicate on the "last_evaluated_at" field.
func LastEvaluatedAtLTE(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldLastEvaluatedAt, v))
}

// LastAlertedAtEQ applies the EQ predicate on the "last_alerted_at" field.
func LastAlertedAtEQ(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldLastAlertedAt, v))
}

// LastAlertedAtNEQ applies the NEQ predicate on the "last_alerted_at" field.
func LastAlertedAtNEQ(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldLastAlertedAt, v))
}

// LastAlertedAtIn applies the In predicate on the "last_alerted_at" field.
func LastAlertedAtIn(vs ...time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldLastAlertedAt, vs...))
}

// LastAlertedAtNotIn applies the NotIn predicate on the "last_alerted_at" field.
func LastAlertedAtNotIn(vs ...time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldLastAlertedAt, vs...))
}

// LastAlertedAtGT applies the GT predicate on the "last_alerted_at" field.
func LastAlertedAtGT(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldLastAlertedAt, v))
}

// LastAlertedAtGTE applies the GTE predicate on the "last_alerted_at" field.
func LastAlertedAtGTE(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldLastAlertedAt, v))
}

// LastAlertedAtLT applies the LT predicate on the "last_alerted_at" field.
func LastAlertedAtLT(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldLastAlertedAt, v))
}

// LastAlertedAtLTE applies the LTE predicate on the "last_alerted_at" field.
func LastAlertedAtLTE(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldLastAlertedAt, v))
}

// LastAlertedAtIsNil applies the IsNil predicate on the "last_alerted_at" field.
func LastAlertedAtIsNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIsNull(FieldLastAlertedAt))
}

// LastAlertedAtNotNil applies the NotNil predicate on the "last_alerted_at" field.
func LastAlertedAtNotNil() predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotNull(FieldLastAlertedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PoolCapacityAlertState) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PoolCapacityAlertState) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PoolCapacityAlertState) predicate.PoolCapacityAlertState {
	return predicate.PoolCapacityAlertState(sql.NotPredicates(p))
}
