// Code generated by ent, DO NOT EDIT.

package announcementemaildelivery

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLTE(FieldID, id))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldJobID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldUserID, v))
}

// RecipientEmail applies equality check predicate on the "recipient_email" field. It's identical to RecipientEmailEQ.
func RecipientEmail(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldRecipientEmail, v))
}

// RecipientName applies equality check predicate on the "recipient_name" field. It's identical to RecipientNameEQ.
func RecipientName(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldRecipientName, v))
}

// Locale applies equality check predicate on the "locale" field. It's identical to LocaleEQ.
func Locale(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldLocale, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldStatus, v))
}

// AttemptCount applies equality check predicate on the "attempt_count" field. It's identical to AttemptCountEQ.
func AttemptCount(v int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldAttemptCount, v))
}

// MaxAttempts applies equality check predicate on the "max_attempts" field. It's identical to MaxAttemptsEQ.
func MaxAttempts(v int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldMaxAttempts, v))
}

// NextAttemptAt applies equality check predicate on the "next_attempt_at" field. It's identical to NextAttemptAtEQ.
func NextAttemptAt(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldNextAttemptAt, v))
}

// LeaseOwner applies equality check predicate on the "lease_owner" field. It's identical to LeaseOwnerEQ.
func LeaseOwner(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldLeaseOwner, v))
}

// LeaseExpiresAt applies equality check predicate on the "lease_expires_at" field. It's identical to LeaseExpiresAtEQ.
func LeaseExpiresAt(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldLeaseExpiresAt, v))
}

// LastErrorClass applies equality check predicate on the "last_error_class" field. It's identical to LastErrorClassEQ.
func LastErrorClass(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldLastErrorClass, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldLastError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldUpdatedAt, v))
}

// SentAt applies equality check predicate on the "sent_at" field. It's identical to SentAtEQ.
func SentAt(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldSentAt, v))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldJobID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLTE(FieldUserID, v))
}

// RecipientEmailEQ applies the EQ predicate on the "recipient_email" field.
func RecipientEmailEQ(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldRecipientEmail, v))
}

// RecipientEmailNEQ applies the NEQ predicate on the "recipient_email" field.
func RecipientEmailNEQ(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldRecipientEmail, v))
}

// RecipientEmailIn applies the In predicate on the "recipient_email" field.
func RecipientEmailIn(vs ...string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldRecipientEmail, vs...))
}

// RecipientEmailNotIn applies the NotIn predicate on the "recipient_email" field.
func RecipientEmailNotIn(vs ...string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldRecipientEmail, vs...))
}

// RecipientEmailGT applies the GT predicate on the "recipient_email" field.
func RecipientEmailGT(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGT(FieldRecipientEmail, v))
}

// RecipientEmailGTE applies the GTE predicate on the "recipient_email" field.
func RecipientEmailGTE(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGTE(FieldRecipientEmail, v))
}

// RecipientEmailLT applies the LT predicate on the "recipient_email" field.
func RecipientEmailLT(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLT(FieldRecipientEmail, v))
}

// RecipientEmailLTE applies the LTE predicate on the "recipient_email" field.
func RecipientEmailLTE(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLTE(FieldRecipientEmail, v))
}

// RecipientEmailContains applies the Contains predicate on the "recipient_email" field.
func RecipientEmailContains(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldContains(FieldRecipientEmail, v))
}

// RecipientEmailHasPrefix applies the HasPrefix predicate on the "recipient_email" field.
func RecipientEmailHasPrefix(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldHasPrefix(FieldRecipientEmail, v))
}

// RecipientEmailHasSuffix applies the HasSuffix predicate on the "recipient_email" field.
func RecipientEmailHasSuffix(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldHasSuffix(FieldRecipientEmail, v))
}

// RecipientEmailEqualFold applies the EqualFold predicate on the "recipient_email" field.
func RecipientEmailEqualFold(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEqualFold(FieldRecipientEmail, v))
}

// RecipientEmailContainsFold applies the ContainsFold predicate on the "recipient_email" field.
func RecipientEmailContainsFold(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldContainsFold(FieldRecipientEmail, v))
}

// RecipientNameEQ applies the EQ predicate on the "recipient_name" field.
func RecipientNameEQ(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldRecipientName, v))
}

// RecipientNameNEQ applies the NEQ predicate on the "recipient_name" field.
func RecipientNameNEQ(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldRecipientName, v))
}

// RecipientNameIn applies the In predicate on the "recipient_name" field.
func RecipientNameIn(vs ...string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldRecipientName, vs...))
}

// RecipientNameNotIn applies the NotIn predicate on the "recipient_name" field.
func RecipientNameNotIn(vs ...string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldRecipientName, vs...))
}

// RecipientNameGT applies the GT predicate on the "recipient_name" field.
func RecipientNameGT(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGT(FieldRecipientName, v))
}

// RecipientNameGTE applies the GTE predicate on the "recipient_name" field.
func RecipientNameGTE(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGTE(FieldRecipientName, v))
}

// RecipientNameLT applies the LT predicate on the "recipient_name" field.
func RecipientNameLT(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLT(FieldRecipientName, v))
}

// RecipientNameLTE applies the LTE predicate on the "recipient_name" field.
func RecipientNameLTE(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLTE(FieldRecipientName, v))
}

// RecipientNameContains applies the Contains predicate on the "recipient_name" field.
func RecipientNameContains(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldContains(FieldRecipientName, v))
}

// RecipientNameHasPrefix applies the HasPrefix predicate on the "recipient_name" field.
func RecipientNameHasPrefix(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldHasPrefix(FieldRecipientName, v))
}

// RecipientNameHasSuffix applies the HasSuffix predicate on the "recipient_name" field.
func RecipientNameHasSuffix(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldHasSuffix(FieldRecipientName, v))
}

// RecipientNameEqualFold applies the EqualFold predicate on the "recipient_name" field.
func RecipientNameEqualFold(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEqualFold(FieldRecipientName, v))
}

// RecipientNameContainsFold applies the ContainsFold predicate on the "recipient_name" field.
func RecipientNameContainsFold(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldContainsFold(FieldRecipientName, v))
}

// LocaleEQ applies the EQ predicate on the "locale" field.
func LocaleEQ(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldLocale, v))
}

// LocaleNEQ applies the NEQ predicate on the "locale" field.
func LocaleNEQ(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldLocale, v))
}

// LocaleIn applies the In predicate on the "locale" field.
func LocaleIn(vs ...string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldLocale, vs...))
}

// LocaleNotIn applies the NotIn predicate on the "locale" field.
func LocaleNotIn(vs ...string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldLocale, vs...))
}

// LocaleGT applies the GT predicate on the "locale" field.
func LocaleGT(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGT(FieldLocale, v))
}

// LocaleGTE applies the GTE predicate on the "locale" field.
func LocaleGTE(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGTE(FieldLocale, v))
}

// LocaleLT applies the LT predicate on the "locale" field.
func LocaleLT(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLT(FieldLocale, v))
}

// LocaleLTE applies the LTE predicate on the "locale" field.
func LocaleLTE(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLTE(FieldLocale, v))
}

// LocaleContains applies the Contains predicate on the "locale" field.
func LocaleContains(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldContains(FieldLocale, v))
}

// LocaleHasPrefix applies the HasPrefix predicate on the "locale" field.
func LocaleHasPrefix(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldHasPrefix(FieldLocale, v))
}

// LocaleHasSuffix applies the HasSuffix predicate on the "locale" field.
func LocaleHasSuffix(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldHasSuffix(FieldLocale, v))
}

// LocaleEqualFold applies the EqualFold predicate on the "locale" field.
func LocaleEqualFold(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEqualFold(FieldLocale, v))
}

// LocaleContainsFold applies the ContainsFold predicate on the "locale" field.
func LocaleContainsFold(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldContainsFold(FieldLocale, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldContainsFold(FieldStatus, v))
}

// AttemptCountEQ applies the EQ predicate on the "attempt_count" field.
func AttemptCountEQ(v int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldAttemptCount, v))
}

// AttemptCountNEQ applies the NEQ predicate on the "attempt_count" field.
func AttemptCountNEQ(v int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldAttemptCount, v))
}

// AttemptCountIn applies the In predicate on the "attempt_count" field.
func AttemptCountIn(vs ...int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldAttemptCount, vs...))
}

// AttemptCountNotIn applies the NotIn predicate on the "attempt_count" field.
func AttemptCountNotIn(vs ...int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldAttemptCount, vs...))
}

// AttemptCountGT applies the GT predicate on the "attempt_count" field.
func AttemptCountGT(v int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGT(FieldAttemptCount, v))
}

// AttemptCountGTE applies the GTE predicate on the "attempt_count" field.
func AttemptCountGTE(v int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGTE(FieldAttemptCount, v))
}

// AttemptCountLT applies the LT predicate on the "attempt_count" field.
func AttemptCountLT(v int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLT(FieldAttemptCount, v))
}

// AttemptCountLTE applies the LTE predicate on the "attempt_count" field.
func AttemptCountLTE(v int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLTE(FieldAttemptCount, v))
}

// MaxAttemptsEQ applies the EQ predicate on the "max_attempts" field.
func MaxAttemptsEQ(v int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldMaxAttempts, v))
}

// MaxAttemptsNEQ applies the NEQ predicate on the "max_attempts" field.
func MaxAttemptsNEQ(v int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldMaxAttempts, v))
}

// MaxAttemptsIn applies the In predicate on the "max_attempts" field.
func MaxAttemptsIn(vs ...int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldMaxAttempts, vs...))
}

// MaxAttemptsNotIn applies the NotIn predicate on the "max_attempts" field.
func MaxAttemptsNotIn(vs ...int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldMaxAttempts, vs...))
}

// MaxAttemptsGT applies the GT predicate on the "max_attempts" field.
func MaxAttemptsGT(v int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGT(FieldMaxAttempts, v))
}

// MaxAttemptsGTE applies the GTE predicate on the "max_attempts" field.
func MaxAttemptsGTE(v int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGTE(FieldMaxAttempts, v))
}

// MaxAttemptsLT applies the LT predicate on the "max_attempts" field.
func MaxAttemptsLT(v int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLT(FieldMaxAttempts, v))
}

// MaxAttemptsLTE applies the LTE predicate on the "max_attempts" field.
func MaxAttemptsLTE(v int) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLTE(FieldMaxAttempts, v))
}

// NextAttemptAtEQ applies the EQ predicate on the "next_attempt_at" field.
func NextAttemptAtEQ(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtNEQ applies the NEQ predicate on the "next_attempt_at" field.
func NextAttemptAtNEQ(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtIn applies the In predicate on the "next_attempt_at" field.
func NextAttemptAtIn(vs ...time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtNotIn applies the NotIn predicate on the "next_attempt_at" field.
func NextAttemptAtNotIn(vs ...time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtGT applies the GT predicate on the "next_attempt_at" field.
func NextAttemptAtGT(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGT(FieldNextAttemptAt, v))
}

// NextAttemptAtGTE applies the GTE predicate on the "next_attempt_at" field.
func NextAttemptAtGTE(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGTE(FieldNextAttemptAt, v))
}

// NextAttemptAtLT applies the LT predicate on the "next_attempt_at" field.
func NextAttemptAtLT(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLT(FieldNextAttemptAt, v))
}

// NextAttemptAtLTE applies the LTE predicate on the "next_attempt_at" field.
func NextAttemptAtLTE(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLTE(FieldNextAttemptAt, v))
}

// LeaseOwnerEQ applies the EQ predicate on the "lease_owner" field.
func LeaseOwnerEQ(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldLeaseOwner, v))
}

// LeaseOwnerNEQ applies the NEQ predicate on the "lease_owner" field.
func LeaseOwnerNEQ(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldLeaseOwner, v))
}

// LeaseOwnerIn applies the In predicate on the "lease_owner" field.
func LeaseOwnerIn(vs ...string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldLeaseOwner, vs...))
}

// LeaseOwnerNotIn applies the NotIn predicate on the "lease_owner" field.
func LeaseOwnerNotIn(vs ...string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldLeaseOwner, vs...))
}

// LeaseOwnerGT applies the GT predicate on the "lease_owner" field.
func LeaseOwnerGT(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGT(FieldLeaseOwner, v))
}

// LeaseOwnerGTE applies the GTE predicate on the "lease_owner" field.
func LeaseOwnerGTE(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGTE(FieldLeaseOwner, v))
}

// LeaseOwnerLT applies the LT predicate on the "lease_owner" field.
func LeaseOwnerLT(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLT(FieldLeaseOwner, v))
}

// LeaseOwnerLTE applies the LTE predicate on the "lease_owner" field.
func LeaseOwnerLTE(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLTE(FieldLeaseOwner, v))
}

// LeaseOwnerContains applies the Contains predicate on the "lease_owner" field.
func LeaseOwnerContains(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldContains(FieldLeaseOwner, v))
}

// LeaseOwnerHasPrefix applies the HasPrefix predicate on the "lease_owner" field.
func LeaseOwnerHasPrefix(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldHasPrefix(FieldLeaseOwner, v))
}

// LeaseOwnerHasSuffix applies the HasSuffix predicate on the "lease_owner" field.
func LeaseOwnerHasSuffix(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldHasSuffix(FieldLeaseOwner, v))
}

// LeaseOwnerIsNil applies the IsNil predicate on the "lease_owner" field.
func LeaseOwnerIsNil() predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIsNull(FieldLeaseOwner))
}

// LeaseOwnerNotNil applies the NotNil predicate on the "lease_owner" field.
func LeaseOwnerNotNil() predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotNull(FieldLeaseOwner))
}

// LeaseOwnerEqualFold applies the EqualFold predicate on the "lease_owner" field.
func LeaseOwnerEqualFold(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEqualFold(FieldLeaseOwner, v))
}

// LeaseOwnerContainsFold applies the ContainsFold predicate on the "lease_owner" field.
func LeaseOwnerContainsFold(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldContainsFold(FieldLeaseOwner, v))
}

// LeaseExpiresAtEQ applies the EQ predicate on the "lease_expires_at" field.
func LeaseExpiresAtEQ(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtNEQ applies the NEQ predicate on the "lease_expires_at" field.
func LeaseExpiresAtNEQ(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtIn applies the In predicate on the "lease_expires_at" field.
func LeaseExpiresAtIn(vs ...time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldLeaseExpiresAt, vs...))
}

// LeaseExpiresAtNotIn applies the NotIn predicate on the "lease_expires_at" field.
func LeaseExpiresAtNotIn(vs ...time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldLeaseExpiresAt, vs...))
}

// LeaseExpiresAtGT applies the GT predicate on the "lease_expires_at" field.
func LeaseExpiresAtGT(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGT(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtGTE applies the GTE predicate on the "lease_expires_at" field.
func LeaseExpiresAtGTE(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGTE(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtLT applies the LT predicate on the "lease_expires_at" field.
func LeaseExpiresAtLT(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLT(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtLTE applies the LTE predicate on the "lease_expires_at" field.
func LeaseExpiresAtLTE(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLTE(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtIsNil applies the IsNil predicate on the "lease_expires_at" field.
func LeaseExpiresAtIsNil() predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIsNull(FieldLeaseExpiresAt))
}

// LeaseExpiresAtNotNil applies the NotNil predicate on the "lease_expires_at" field.
func LeaseExpiresAtNotNil() predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotNull(FieldLeaseExpiresAt))
}

// LastErrorClassEQ applies the EQ predicate on the "last_error_class" field.
func LastErrorClassEQ(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldLastErrorClass, v))
}

// LastErrorClassNEQ applies the NEQ predicate on the "last_error_class" field.
func LastErrorClassNEQ(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldLastErrorClass, v))
}

// LastErrorClassIn applies the In predicate on the "last_error_class" field.
func LastErrorClassIn(vs ...string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldLastErrorClass, vs...))
}

// LastErrorClassNotIn applies the NotIn predicate on the "last_error_class" field.
func LastErrorClassNotIn(vs ...string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldLastErrorClass, vs...))
}

// LastErrorClassGT applies the GT predicate on the "last_error_class" field.
func LastErrorClassGT(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGT(FieldLastErrorClass, v))
}

// LastErrorClassGTE applies the GTE predicate on the "last_error_class" field.
func LastErrorClassGTE(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGTE(FieldLastErrorClass, v))
}

// LastErrorClassLT applies the LT predicate on the "last_error_class" field.
func LastErrorClassLT(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLT(FieldLastErrorClass, v))
}

// LastErrorClassLTE applies the LTE predicate on the "last_error_class" field.
func LastErrorClassLTE(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLTE(FieldLastErrorClass, v))
}

// LastErrorClassContains applies the Contains predicate on the "last_error_class" field.
func LastErrorClassContains(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldContains(FieldLastErrorClass, v))
}

// LastErrorClassHasPrefix applies the HasPrefix predicate on the "last_error_class" field.
func LastErrorClassHasPrefix(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldHasPrefix(FieldLastErrorClass, v))
}

// LastErrorClassHasSuffix applies the HasSuffix predicate on the "last_error_class" field.
func LastErrorClassHasSuffix(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldHasSuffix(FieldLastErrorClass, v))
}

// LastErrorClassIsNil applies the IsNil predicate on the "last_error_class" field.
func LastErrorClassIsNil() predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIsNull(FieldLastErrorClass))
}

// LastErrorClassNotNil applies the NotNil predicate on the "last_error_class" field.
func LastErrorClassNotNil() predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotNull(FieldLastErrorClass))
}

// LastErrorClassEqualFold applies the EqualFold predicate on the "last_error_class" field.
func LastErrorClassEqualFold(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEqualFold(FieldLastErrorClass, v))
}

// LastErrorClassContainsFold applies the ContainsFold predicate on the "last_error_class" field.
func LastErrorClassContainsFold(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldContainsFold(FieldLastErrorClass, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldContainsFold(FieldLastError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLTE(FieldUpdatedAt, v))
}

// SentAtEQ applies the EQ predicate on the "sent_at" field.
func SentAtEQ(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldEQ(FieldSentAt, v))
}

// SentAtNEQ applies the NEQ predicate on the "sent_at" field.
func SentAtNEQ(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNEQ(FieldSentAt, v))
}

// SentAtIn applies the In predicate on the "sent_at" field.
func SentAtIn(vs ...time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIn(FieldSentAt, vs...))
}

// SentAtNotIn applies the NotIn predicate on the "sent_at" field.
func SentAtNotIn(vs ...time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotIn(FieldSentAt, vs...))
}

// SentAtGT applies the GT predicate on the "sent_at" field.
func SentAtGT(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGT(FieldSentAt, v))
}

// SentAtGTE applies the GTE predicate on the "sent_at" field.
func SentAtGTE(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldGTE(FieldSentAt, v))
}

// SentAtLT applies the LT predicate on the "sent_at" field.
func SentAtLT(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLT(FieldSentAt, v))
}

// SentAtLTE applies the LTE predicate on the "sent_at" field.
func SentAtLTE(v time.Time) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldLTE(FieldSentAt, v))
}

// SentAtIsNil applies the IsNil predicate on the "sent_at" field.
func SentAtIsNil() predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldIsNull(FieldSentAt))
}

// SentAtNotNil applies the NotNil predicate on the "sent_at" field.
func SentAtNotNil() predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.FieldNotNull(FieldSentAt))
}

// HasJob applies the HasEdge predicate on the "job" edge.
func HasJob() predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, JobTable, JobColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasJobWith applies the HasEdge predicate on the "job" edge with a given conditions (other predicates).
func HasJobWith(preds ...predicate.AnnouncementEmailJob) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(func(s *sql.Selector) {
		step := newJobStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AnnouncementEmailDelivery) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AnnouncementEmailDelivery) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AnnouncementEmailDelivery) predicate.AnnouncementEmailDelivery {
	return predicate.AnnouncementEmailDelivery(sql.NotPredicates(p))
}
