package modelerror

var catalogChinese = map[Code]string{
	CodeAuthRequired:         "缺少 API Key，请将密钥放入 Authorization 请求头后重试。",
	CodeAuthInvalid:          "API Key 无效，请检查密钥和接口地址是否正确后重试。",
	CodeAuthDisabled:         "此 API Key 已停用，请启用该密钥或更换其他有效密钥。",
	CodeAuthExpired:          "此 API Key 已过期，请续期或更换其他有效密钥。",
	CodeAuthUnavailable:      "API Key 鉴权服务暂时不可用，请稍后重试。",
	CodePermissionDenied:     "当前密钥、用户、分组或网络策略不允许此请求，请检查授权后重试。",
	CodeQuotaExhausted:       "可用 API 额度已用完，请补充额度、续订套餐或更换其他密钥。",
	CodeBalanceInsufficient:  "账户余额不足以完成本次请求，请充值或使用其他可用套餐。",
	CodeSubscriptionRequired: "当前分组没有有效订阅，请开通订阅或选择其他分组。",
	CodeUsageLimitExceeded:   "当前订阅用量已达到上限，请等待用量窗口重置或更换其他套餐。",
	CodeGroupUnavailable:     "所选分组不可用或未分配给此密钥，请更换分组或联系管理员。",
	CodeEndpointNotAllowed:   "所选分组不允许使用此接口协议，请更换允许的接口或分组。",
	CodeInvalidRequest:       "模型请求格式无效，请检查模型名称、请求字段、工具定义和消息结构。",
	CodePayloadTooLarge:      "请求内容过大，请减少附件或请求正文后重试。",
	CodeModelRequired:        "缺少模型名称，请设置 model 字段后重试。",
	CodeModelUnsupported:     "当前分组不支持所请求的模型，请检查模型名称或更换分组。",
	CodeModelNotFound:        "未找到所请求的模型，或当前分组尚未配置该模型，请检查模型名称或分组配置。",
	CodeContextTooLarge:      "输入内容超过模型上下文限制，请缩短对话、提示词或附件后重试。",
	CodeConcurrencyLimit:     "当前并发已达到上限，请等待正在执行的请求完成后重试。",
	CodeQueueFull:            "等待中的请求过多，请稍后重试。",
	CodeRateLimited:          "请求频率过高，请按退避策略稍后重试。",
	CodeContentPolicy:        "请求被内容或安全策略拦截，请调整输入内容后重试。",
	CodeUpstreamAuthFailed:   "上游模型账号认证失败，请联系管理员检查渠道凭据。",
	CodeUpstreamForbidden:    "上游模型账号没有执行此请求的权限，请联系管理员或更换模型/渠道。",
	CodeUpstreamRateLimited:  "上游模型服务触发限流，请稍后退避重试或更换其他可用渠道。",
	CodeUpstreamOverloaded:   "上游模型服务当前负载过高，请稍后重试或更换其他可用渠道。",
	CodeUpstreamTimeout:      "上游模型服务未能在时限内完成请求，请稍后重试或降低请求复杂度。",
	CodeUpstreamUnavailable:  "上游模型服务暂时不可用，请稍后重试或更换其他可用渠道。",
	CodeUpstreamBadResponse:  "上游模型服务返回了无效响应，请稍后重试；若持续发生，请联系管理员。",
	CodeServiceUnavailable:   "模型服务暂时不可用，请稍后重试；若持续发生，请联系管理员。",
	CodeInternalError:        "服务暂时无法完成请求，请稍后重试；若持续发生，请向管理员提供请求 ID。",
}
