package modelerror

var catalogEnglish = map[Code]string{
	CodeAuthRequired:         "An API key is required. Add it to the Authorization header and try again.",
	CodeAuthInvalid:          "The API key is invalid. Check the configured key and endpoint, then try again.",
	CodeAuthDisabled:         "This API key is disabled. Enable it or use another active key.",
	CodeAuthExpired:          "This API key has expired. Renew it or use another active key.",
	CodeAuthUnavailable:      "API key authentication is temporarily unavailable. Please retry shortly.",
	CodePermissionDenied:     "This request is not allowed by the current key, user, group, or network policy.",
	CodeQuotaExhausted:       "The available API quota has been exhausted. Add quota, renew the plan, or use another key.",
	CodeBalanceInsufficient:  "The account balance is insufficient for this request. Add balance or use an eligible plan.",
	CodeSubscriptionRequired: "No active subscription is available for this group. Activate a subscription or choose another group.",
	CodeUsageLimitExceeded:   "The current subscription usage limit has been reached. Retry after the usage window resets or use another plan.",
	CodeGroupUnavailable:     "The selected group is unavailable or not assigned to this key. Choose another group or contact the administrator.",
	CodeEndpointNotAllowed:   "The selected group does not allow this API protocol. Use a permitted endpoint or choose another group.",
	CodeInvalidRequest:       "The model request is invalid. Check the model name, request fields, tool definitions, and message structure.",
	CodePayloadTooLarge:      "The request payload is too large. Reduce attachments or request content and try again.",
	CodeModelRequired:        "A model name is required. Set the model field and try again.",
	CodeModelUnsupported:     "The requested model is not supported by the current group. Check the model name or choose another group.",
	CodeModelNotFound:        "The requested model was not found or is not configured for the current group. Check the model name or group configuration.",
	CodeContextTooLarge:      "The input exceeds the model context limit. Shorten the conversation, prompt, or attachments and try again.",
	CodeConcurrencyLimit:     "The concurrency limit has been reached. Wait for an active request to finish and retry.",
	CodeQueueFull:            "Too many requests are waiting. Retry after a short delay.",
	CodeRateLimited:          "Requests are arriving too quickly. Retry with backoff.",
	CodeContentPolicy:        "The request was blocked by a content or security policy. Revise the input and try again.",
	CodeUpstreamAuthFailed:   "The upstream model account failed authentication. Contact the administrator to check the channel credentials.",
	CodeUpstreamForbidden:    "The upstream model account does not have permission for this request. Contact the administrator or use another model/channel.",
	CodeUpstreamRateLimited:  "The upstream model service is rate-limited. Retry with backoff or use another available channel.",
	CodeUpstreamOverloaded:   "The upstream model service is overloaded. Retry later or use another available channel.",
	CodeUpstreamTimeout:      "The upstream model service timed out before completing the request. Retry later or reduce request complexity.",
	CodeUpstreamUnavailable:  "The upstream model service is temporarily unavailable. Retry later or use another available channel.",
	CodeUpstreamBadResponse:  "The upstream model service returned an invalid response. Retry later; if it continues, contact the administrator.",
	CodeServiceUnavailable:   "The model service is temporarily unavailable. Retry later; if it continues, contact the administrator.",
	CodeInternalError:        "The service could not complete the request. Retry later; if it continues, provide the request ID to the administrator.",
}
